104 user authentication
martinjonsson01/contract-portal pull request #113
Opened 2022-05-06 16:35 UTC by jonathan-lindqvist

## Summary
A password is now required to login. Verification is done by bcrypt
![image](https://user-images.githubusercontent.com/47867973/167174798-00a88dc2-e456-4496-b20f-4e104bb848fe.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #104

2022-05-06 18:41 UTC, martinjonsson01 requested changes
Looking good, I've got a few comments.

Regarding the UI design:
I think you should change the header on the login modal now that there are multiple input fields, to maybe something like "Logga in".

2022-05-06 18:41 UTC, martinjonsson01 commented on .github/workflows/dotnet.yml
> +    prodigo_portal_admin_password: "test_password"
You should add this into `appsettings.Development.json` as well, because that way we don't have to set up an environment variable for it at all (except for on Azure, because that's when it's actually secret).

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Application/Users/InvalidPasswordException.cs
> +public class InvalidPasswordException : Exception
😍 
great use of a custom exception! This leads to much more descriptive errors than "InvalidArgumentException" and so on

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Application/Users/UserService.cs
> +    private static bool ValidPassword(User user, string password)
nit:
Rather than a noun, I think it's better to name these truthy/falsey methods like a question, e.g. `IsPasswordValid` rather than `ValidPassword`. I'd name a variable containing a valid password `validPassword`, but not a method.

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Application/Users/UserService.cs
> +    private static bool ValidPassword(User user, string password)
(btw, nice use of a method-wrapper around the very verbose BCrypt-call, it makes the `Authenticate` method much easier to read!)

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFUserRepository.cs
> +        string? adminPasswordSecret = Environment.GetEnvironmentVariable(ConfigurationKeys.AdminPassword);
Whenever possible, avoid using `Environment.GetEnvironmentVariable(...)`. It's very hard to mock these during tests and they're not very easy to work with generally. 

Instead, use an injected `IConfiguration` instance, like we've done in `UserService`:
https://github.com/martinjonsson01/contract-portal/blob/69017de75f3d7f10b8d1c3124db9f3a9c51e96ab/src/Application/Users/UserService.cs#L92

The great benefit of this is 1) that if no environment variable with that key exists, it'll take the value from `appsettings.{Environment}.json`, 2) it allows us to overwrite them in tests, and most importantly 3) the value in appsettings is always overriden by the one in an environment variable (if it exists), so this allows us to have default values used during development that can be overridden when deploying.

The only place where we should manually load environment variables is inside of the [EFDatabaseContextFactory.cs](https://github.com/martinjonsson01/contract-portal/blob/master/src/Infrastructure/EFDatabaseContextFactory.cs) class, since it isn't a part of our dependency injection container and can't have access to `IConfiguration`.

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFUserRepository.cs
> +        Console.WriteLine(adminPasswordSecret);
Debugging artifacts 😩 
```suggestion
        adminPasswordSecret = BCrypt.Net.BCrypt.HashPassword(adminPasswordSecret);
```

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/20220506150041_AddPasswordToUser.cs
> +}
When merging with #105 you'll have to choose one of your migrations and stick with it, we can't keep both. (Just a heads up)

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Server/Controllers/UsersController.cs
> +    /// <param name="userInfo">The username and password.</param>
nit:
```suggestion
    /// <param name="userInfo">The user to authenticate.</param>
```

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Server/Controllers/UsersController.cs
> +    public IActionResult Authenticate(User userInfo)
nit:
It's not really user info since it's an actual user instance, so just `User user` fits better imo

2022-05-06 18:41 UTC, martinjonsson01 commented on src/Server/Controllers/UsersController.cs
> +            }
When you have to catch multiple exceptions this might seem like a good way to do it, but it's an anti-pattern.

The correct way to do it is the following:

```csharp
try 
{
    // Code here
}
catch (FirstExceptionType)
{
    // Log a specific message and return bad request
}
catch (ThirdExceptionType)
{
    // Log a specific message and return bad request
}
catch (FourthExceptionType)
{
    // Log a specific message and return bad request
}
```

(And as an aside, I realize now that we can be much more specific about what we're logging here, since the exceptions we're catching are specific. E.g. "Can't authenticate a user that does not exist" and "An incorrect password was given for the user" or similar)

2022-05-06 18:41 UTC, martinjonsson01 commented on tests/Application.Tests/Users/UserServiceTests.cs
> +        _mockRepo.Setup(repository => repository.All).Returns(new[] { user, });
🙏

2022-05-06 18:41 UTC, martinjonsson01 commented on tests/Application.Tests/Users/UserServiceTests.cs
> +        _mockRepo.Setup(repository => repository.Fetch(user.Name)).Returns(user);
When merging with #104 then these tests should be rewritten to take advantage of the `Add` functionality implemented there where it encrypts the password.

2022-05-06 18:41 UTC, martinjonsson01 commented on tests/Application.Tests/Users/UserServiceTests.cs
> +    public void ValidatePassword_shouldBeFalse_WhenPasswordIsNotUserPassword()
nit:
```suggestion
    public void ValidatePassword_ShouldBeFalse_WhenPasswordIsNotUserPassword()
```

2022-05-06 18:41 UTC, martinjonsson01 commented on tests/Application.Tests/Users/UserServiceTests.cs
> +    public void ValidatePassword_shouldBeTrue_WhenPasswordIsUserPassword()
nit:
```suggestion
    public void ValidatePassword_ShouldBeTrue_WhenPasswordIsUserPassword()
```

2022-05-06 18:41 UTC, martinjonsson01 commented on tests/Application.Tests/Users/UserServiceTests.cs
> +        const string password2 = "User2Password";
nit:
To make the test a bit more easier to understand you could be more specific:
```suggestion
        const string correctPassword = "CorrectPassword";
        const string incorrectPassword = "IncorrectPassword";
```

2022-05-06 18:41 UTC, martinjonsson01 commented on tests/Presentation.Tests/Server/Authentication/AuthIntegrationTests.cs
> +        var userInfo = new User() { Name = "admin", Password = Environment.GetEnvironmentVariable(ConfigurationKeys.AdminPassword), };
Is it possible to write this test without relying on an environment variable? I can imagine this being a pain in the future.

2022-05-06 18:41 UTC, martinjonsson01 commented on tests/Presentation.Tests/Server/Controllers/UsersControllerTests.cs
> +    public void Authenticate_ReturnsBadRequest_IfUserDoesNotExist()
nit:
If the request is correctly formatted, but what is failing is the validation of the given credentials, then I think a more fitting status code is `401 (Unauthorized)` since they failed to be authorized access.

2022-05-07 04:26 UTC, martinjonsson01 commented on tests/Presentation.Tests/Server/Authentication/AuthIntegrationTests.cs
> +        var userInfo = new User() { Name = "admin", Password = Environment.GetEnvironmentVariable(ConfigurationKeys.AdminPassword), };
I found a way to solve this, you can override environment variables in a test by setting the environment variables specifically for the current process:
```csharp
Environment.SetEnvironmentVariable(
            ConfigurationKeys.AdminPassword,
            "test-admin-password",
            EnvironmentVariableTarget.Process);
```

2022-05-07 12:51 UTC, martinjonsson01 approved these changes
lgtm 👍

2022-05-07 12:51 UTC, martinjonsson01 commented on src/Server/Controllers/UsersController.cs
> +    /// <param name="user">The user to authentication.</param>
nit:
```suggestion
    /// <param name="user">The user to authenticate.</param>
```

2022-05-08 15:30 UTC, ellsib approved these changes
LGTM 👍 Left two comments.

2022-05-08 15:30 UTC, ellsib commented on src/Domain/Users/User.cs
> +    public string? Password { get; set; } = "verysecurepassword";
What does this do? :) Password should never be left out, so there will always be another specific password, right?

2022-05-08 15:30 UTC, ellsib commented on src/Infrastructure/Migrations/20220506150041_AddPasswordToUser.Designer.cs
> +
Isn't the stuff in here already done in the user story #105?

2022-05-08 15:32 UTC, martinjonsson01 commented on src/Domain/Users/User.cs
> +    public string? Password { get; set; } = "verysecurepassword";
I just noticed, how come the password is nullable, @jonathan-lindqvist?

2022-05-08 15:37 UTC, ellsib commented on src/Domain/Users/User.cs
> +    public string? Password { get; set; } = "verysecurepassword";
> (unrelated to above comment) I just noticed, how come the password is nullable, @jonathan-lindqvist?

Yes I was wondering about that too

2022-05-08 15:41 UTC, martinjonsson01 commented on src/Domain/Users/User.cs
> +    public string? Password { get; set; } = "verysecurepassword";
> Yes I was wondering about that too

Oh, I thought you meant the default value "verysecurepassword"

2022-05-08 15:43 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/20220506150041_AddPasswordToUser.Designer.cs
> +
Is this a duplicate of my comment [here](https://github.com/martinjonsson01/contract-portal/pull/113#discussion_r867071030), or did you mean something else?

2022-05-08 15:48 UTC, ellsib commented on src/Domain/Users/User.cs
> +    public string? Password { get; set; } = "verysecurepassword";
Haha my bad. I was wondering both about why you have a default value when no user will ever have the default value AND then why this is allowed to be null :)

2022-05-08 16:18 UTC, martinjonsson01 commented on src/Domain/Users/User.cs
> +    public string? Password { get; set; } = "verysecurepassword";
Hm, it's a bit tricky since we either allow null values or we don't, but if we don't then we *have* to provide a default value since otherwise it will be null which we aren't allowing. Another one of these fun catch-22s 😝 

Either way, we should decide on having it nullable without a default value, or non-nullable with a default value. The downside to having it nullable is that every time we read it we have to handle the case of it being null, even though we may know that they're never null. The downside with it having a default value is that if you're somehow able to create a user without specifying a password then they'll get a (possibly insecure) default password.

I'm leaning toward the default-route, since we can enforce in the code that a password is always supplied, to overwrite the default value.

2022-05-09 12:58 UTC, jonathan-lindqvist commented on tests/Application.Tests/Users/UserServiceTests.cs
> +        _mockRepo.Setup(repository => repository.Fetch(user.Name)).Returns(user);
Will have to mock it either way

2022-05-09 12:58 UTC, merged