100 restricted contract details
martinjonsson01/contract-portal pull request #116
Opened 2022-05-07 12:46 UTC by martinjonsson01

## Summary
Makes contract details restricted, instead showing a call to action to register an account.
![chrome_pOqaUfMsEW](https://user-images.githubusercontent.com/12572888/167254182-ec64fde5-a765-40e3-8e23-7bb85c37c782.gif)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #100

2022-05-07 14:11 UTC, jonathan-lindqvist approved these changes
Neat, just one comment about adding keys that would be nice! But it all looks good 😄

2022-05-07 14:11 UTC, jonathan-lindqvist commented on src/Client/Pages/Contracts/ContractsPage.razor
> +                </div>
Since we are changing the cards we could also add `@Key=contract` to each card to optimize the site a bit.

Here are some useful links if you want to read more about it: [blazor university](https://blazor-university.com/components/render-trees/optimising-using-key/) and [microsoft](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#use-key-to-control-the-preservation-of-elements-and-components)

2022-05-07 14:11 UTC, jonathan-lindqvist commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +                        }
See previous comment about key

2022-05-07 14:11 UTC, jonathan-lindqvist commented on src/Server/Controllers/ContractsController.cs
> +    [AllowAnonymous]
![image](https://user-images.githubusercontent.com/47867973/167257893-dd33b73d-f644-4b26-9a11-7d7fae05ed53.png)

2022-05-07 14:37 UTC, martinjonsson01 commented on src/Application/Contracts/ContractService.cs
> +    }
![image](https://user-images.githubusercontent.com/12572888/167258922-08f9fde9-f5f9-420d-bb91-ea2d533960ed.png)

2022-05-07 14:44 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/ContractsPage.razor
> +                </div>
Interesting! I believe the reason I haven't used it before in Blazor is because it's not necessary in most cases, as stated [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#when-not-to-use-key):
># When not to use @key
>There's a performance cost when rendering with [@key](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#key). The performance cost isn't large, but only specify @key if preserving the element or component benefits the app.

>Even if [@key](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#key) isn't used, Blazor preserves child element and component instances as much as possible. The only advantage to using @key is control over how model instances are mapped to the preserved component instances, instead of Blazor selecting the mapping.

So it's basically only necessary when, like in the example they gave with the focus shifting, there is a noticeable impact on the user experience due to element instances being shifted around. This is good for us, because it means that we don't have to go back to all our previous lists and fix them lol

2022-05-07 14:46 UTC, martinjonsson01 commented on src/Server/Controllers/ContractsController.cs
> +    [AllowAnonymous]
> me, adding an attribute to a controller method

![image](https://user-images.githubusercontent.com/12572888/167259292-04a6bbf3-8dcc-478c-8640-7809a2dbca7b.png)

2022-05-08 11:18 UTC, jonathan-lindqvist commented on src/Client/Pages/Contracts/ContractsPage.razor
> +                </div>
👍

2022-05-08 15:12 UTC, XwayTomy requested changes
Looks good! I just have one thing that I believe should be changed. When an unauthorized person opens a contract card, the first accordion should be closed in order to not reveal any further information about the contract.

2022-05-08 16:01 UTC, XwayTomy approved these changes
LGTM!

2022-05-08 16:19 UTC, merged