87 show personalized favorites
martinjonsson01/contract-portal pull request #131
Opened 2022-05-09 13:52 UTC by JacobBredin

## Summary
Favorites are now saved in the database for each user separately. Favorites are also shown to users based on what they have favorited themselves.

![image](https://user-images.githubusercontent.com/70701264/167419970-afd78ba8-df7f-43fe-a4d7-025c333f8195.png)

(images via SQL Server Management Studio)
![image](https://user-images.githubusercontent.com/70701264/167420109-47517d77-15c8-4cb2-a74e-19e3608f034f.png)
![image](https://user-images.githubusercontent.com/70701264/167420436-d005049f-48bc-4fc4-8b09-14307d940f01.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #87

2022-05-09 14:18 UTC, jonathan-lindqvist commented on tests/Application.Tests/Favorites/FavoriteContractServiceTests.cs
> +    public void CheckIfFavorite_ReturnsTrue_IfContractIsMarkedAsFavorite()
If we change the name to IsFavorite then the test names should be updated aswell

2022-05-09 14:22 UTC, JacobBredin commented on src/Application/MessagePassing/SetFavoriteContract.cs
> +    public bool IsFavorite { get; init; }
hmm?

2022-05-09 14:28 UTC, martinjonsson01 commented on src/Domain/Contracts/Contract.cs
> +#pragma warning restore CA2227 // Collection properties should be read only
This seems really backwards, and shouldn't have to be in the domain model. To configure the database, try using the fluent API instead, which should allow you to do this. 

[This](https://stackoverflow.com/questions/16718699/map-many-to-many-relationship-without-navigation-property) looks very applicable.

2022-05-09 14:47 UTC, XwayTomy approved these changes
This was a big boi PR and I had a bit of a hard time reviewing it because of the complexity between all the different parts of the program. Left one small question but other than that everything looked good to my eyes!

2022-05-09 14:47 UTC, XwayTomy commented on src/Application/MessagePassing/SetFavoriteContract.cs
> +    public bool IsFavorite { get; init; }
Don't fall for the sabotage attempt :O @JacobBredin

2022-05-09 14:47 UTC, XwayTomy commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +        SetFavoriteContract setFavorite = new() { UserName = LoggedInUser!, ContractId = Contract.Id, IsFavorite = !isFavorite };
What is the difference between "IsFavorite" and "isFavorite"? Shouldn't those be the same?

2022-05-09 15:15 UTC, JacobBredin commented on src/Infrastructure/Databases/EFFavoriteRepository.cs
> +    }
Sure, however `Add` and `Remove` would still need to have access to `IDatabaseContext`, since they need to use `SaveChanges`. Should I keep them in the repo and move everything else out into the service? Adding methods to `UserRepo` for adding and removing contracts feels like adding too much responsibility to `UserRepo`.

2022-05-09 16:20 UTC, martinjonsson01 requested changes
Looking good, I think there are a few modifications that need to be made and then it's ready to go! 🚀

2022-05-09 16:20 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Favorites/FavoriteRepositoryTests.cs
> +        contracts.Where(c => c.Id == contract.Id).Should().NotBeNull();
nit:
What you're fetching here are not the contracts, it's a list of users that *include* the contracts. Because of this you've incorrectly asserted. The assertion still succeeds because you're asserting that `.Where(....).Should().NotBeNull()` but `.Where()` returns an empty collection when it doesn't match on anything, so since an empty collection isn't null then the test still passes (even though it shouldn't).

```suggestion
        var databaseUser = _context.Users.Find(user.id).Include(u => u.Contracts);
        databaseUser.Contracts.Should().Contain(contract);
```

2022-05-09 16:20 UTC, martinjonsson01 commented on tests/Server.Tests/Controllers/FavoritesControllerTests.cs
> +    public void Change_ReturnsOk()
It doesn't seem like you're testing that `Change` should return `BadRequest` when the two exceptions are thrown, is that intentional?

2022-05-09 20:04 UTC, JacobBredin commented on src/Domain/Contracts/Contract.cs
> +#pragma warning restore CA2227 // Collection properties should be read only
Sadly that solution does not work anymore. Currently the navigation property is required by EF. However I found this solution that hides the Collection of users in contract:
https://github.com/dotnet/efcore/issues/3864#issuecomment-749981539

It also has the added benefit that the user list doesn't have to be dereferenced when serialized.

2022-05-10 03:15 UTC, martinjonsson01 commented on src/Domain/Contracts/Contract.cs
> +#pragma warning restore CA2227 // Collection properties should be read only
Ah, that really is too bad. Oh well, making it private is at least much better than having it be public! You should replace the documentation on it (since it isn't required when it's private) with a normal comment explaining that that property is not supposed to be there, that it only has to be there to create the many-to-many relationship.

2022-05-11 11:44 UTC, jonathan-lindqvist approved these changes
Looking great! 👍 

Nothing to comment on that has not already been mentioned

2022-05-12 14:03 UTC, martinjonsson01 approved these changes
Good work!

2022-05-12 14:03 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/Contracts/FavoriteButtonTests.cs
> +        MockHttp.When($"/api/v1/users/{userName}/favorites/{contract.Id}").Respond(req => new HttpResponseMessage(HttpStatusCode.OK)); // The contract is marked as favorite
nit:
Did you try simplifying it like this?
```suggestion
        MockHttp.When($"/api/v1/users/{userName}/favorites/{contract.Id}").Respond(HttpStatusCode.OK); // The contract is marked as favorite
```

2022-05-12 14:03 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/Contracts/FavoriteButtonTests.cs
> +        MockHttp.When(HttpMethod.Post, $"/api/v1/users/{userName}/favorites").Respond(req => new HttpResponseMessage(HttpStatusCode.OK)); // The contract does get unmarked
Yeah, this looks kind of backwards, right? Since when you're calling `users/username/favorites` you want to *get* all of the favorites of a single user, and when you're calling `users/username/favorites/specificcontractid` you're trying to *post* a new value.

Maybe I'm the one that's thinking backwards here, but you should double-check.

2022-05-12 14:07 UTC, martinjonsson01 commented on src/Application/Users/IUserService.cs
> +    bool RemoveFavorite(string userName, Guid contractId);
Yeah that's the problem with huge PRs like this. 

(later = never)

2022-05-12 14:14 UTC, martinjonsson01 commented on src/Application/Users/IUserService.cs
> +    bool RemoveFavorite(string userName, Guid contractId);
😭

2022-05-12 14:24 UTC, JacobBredin commented on tests/Client.Tests/Pages/Contracts/FavoriteButtonTests.cs
> +        MockHttp.When(HttpMethod.Post, $"/api/v1/users/{userName}/favorites").Respond(req => new HttpResponseMessage(HttpStatusCode.OK)); // The contract does get unmarked
If you look at it as `users/username/favorites` being a "bag" of favorites, I think it makes sense that you post new favorites to the bag, instead of posting to a specific favorite that does not yet exist. I think both ways work.

2022-05-12 14:28 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/Contracts/FavoriteButtonTests.cs
> +        MockHttp.When(HttpMethod.Post, $"/api/v1/users/{userName}/favorites").Respond(req => new HttpResponseMessage(HttpStatusCode.OK)); // The contract does get unmarked
Yeah, that's fair, and I think that's how it usually works with `POST`. I thought for a second there that you had your `Change` controller method mapped to `/favorites/{contractid}` since you want to change the status for a single favorite rather than the bag of favorites.

2022-05-12 14:47 UTC, pkasinski commented on tests/Client.Tests/Pages/Contracts/FavoriteButtonTests.cs
> +        MockHttp.When($"/api/v1/users/{userName}/favorites/{contract.Id}").Respond(req => new HttpResponseMessage(HttpStatusCode.OK)); // The contract is marked as favorite
I think it is correct. The one above checks if the contract is marked as favorite and gets a confirmation that it is marked as favorite and the one below tries to unmark the favorite but is not successful.

2022-05-13 07:54 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +        if (!string.IsNullOrEmpty(_session.Username))
nit:
To make the code more readable, use the new `IsAuthenticated` property in the session service!

2022-05-13 07:54 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +        if (!string.IsNullOrEmpty(_session.Username))
nit:
To make the code more readable, use the new `IsAuthenticated` property in the session service!

2022-05-13 08:43 UTC, pkasinski commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +        if (!string.IsNullOrEmpty(_session.Username))
In this case there is a "Possible null reference assignment." error when the username is set to _session.Username.

2022-05-13 08:45 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +        if (!string.IsNullOrEmpty(_session.Username))
Fair enough 👍

2022-05-14 11:40 UTC, merged