106 welcome page
martinjonsson01/contract-portal pull request #137
Opened 2022-05-11 12:13 UTC by Gigset

## Summary
This pull request adds a welcome page to the site, including a welcome text and a link to the official Prodigo Site.

https://user-images.githubusercontent.com/73949651/167846806-9dbd4566-2093-45e0-90d2-e47fbd99185b.mp4

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #106-welcome-page

2022-05-11 12:23 UTC, XwayTomy submitted a review, later dismissed
Looks good apart from two small things:
- The border above the picture looks weird. I think the picture should cover the entire area.
- The letter p and r where it says "prodigo" are not clearly visible. Perhaps a border or a black outline could fix this?

Good job!

2022-05-11 12:23 UTC, martinjonsson01 requested changes
Looking great! I mainly want you to remove the unnecessary HTML-elements in the page, the rest are just nits.

2022-05-11 12:23 UTC, martinjonsson01 commented on src/Server/Properties/launchSettings.json
> +                "prodigo_portal_jwt_secret":"secret",
nit:
Is this necessary? Weren't you able to set it as an environment variable?

2022-05-11 12:23 UTC, martinjonsson01 commented on src/Client/Pages/WelcomePage.razor
> +<body>
You don't need the `head` and `body` tags, they're mostly used at the root of the HTML-page (which we've already got). 

But everything should look the same (or maybe this removes the padding at the top, which would be nice) without them!

2022-05-11 12:23 UTC, martinjonsson01 commented on src/Client/Pages/WelcomePage.razor
> +</body>
Don't forget to remove this one as well.

2022-05-11 12:23 UTC, martinjonsson01 commented on src/Client/Pages/WelcomePage.razor.css
> +    padding-right:10px;
nit:
Try to use `rem` units wherever possible! Pixels are good when you want to get stuff pixel-perfect, but they're rarely pixel-perfect on every screen size and resolution, so it's better to go with the more flexible `rem` units.

2022-05-11 12:23 UTC, martinjonsson01 commented on src/Client/Pages/WelcomePage.razor.css
> +
nit:
```suggestion
```

2022-05-11 12:23 UTC, martinjonsson01 commented on src/Client/Pages/WelcomePage.razor.css
> +.text-block {
nit:
Try running the auto formatter on this file, there are a few missing spaces here and there! :)

2022-05-11 14:51 UTC, Gigset commented on src/Client/Pages/WelcomePage.razor
> +<body>
Done, unfortunately it did not remove the top padding :(

2022-05-12 13:33 UTC, jonathan-lindqvist approved these changes
Nice!

2022-05-12 13:45 UTC, martinjonsson01 commented on src/Client/Pages/WelcomePage.razor
> +            <button class="btn btn-primary" style="top:50px;position:relative;width: 200px;height: 50px;">
nit:
It's more readable to put the styling in a component-scoped stylesheet (e.g. `WelcomePage.razor.css`) rather than as inline-styling! (Also, did you forget to swap out the pixel-units here?)

2022-05-12 13:45 UTC, martinjonsson01 commented on src/Client/Pages/WelcomePage.razor
>  }
nit:
You don't need the code-block at all if you don't have any code in it. :)

2022-05-13 12:08 UTC, merged