88 show personalized recents
martinjonsson01/contract-portal pull request #144
Opened 2022-05-13 15:52 UTC by Matte02

## Summary
I think I have caught most of the bugs, but would probably be good if you could run the application and see if you can find any, that I might have missed.  

This PR will make recent contracts personalized. Currently, only 3 contracts are stored, this can be changed in `RecentContractService` .  

![chrome_sjPeQvTVHE](https://user-images.githubusercontent.com/55716109/168314935-6966dc11-1c55-40f5-b1d0-aa7e0c2e86a0.gif)

![chrome_AxNFsoXU3K](https://user-images.githubusercontent.com/55716109/168316745-05eea253-48a1-4c76-993e-e0d6aa7ac2c7.gif)

Tests: 
![image](https://user-images.githubusercontent.com/55716109/168320972-aaf972f6-60fc-4af5-8159-2052add73a5d.png)

![image](https://user-images.githubusercontent.com/55716109/168320993-96ea475e-a5e7-4bbd-9bb3-111d2f22b0e3.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Close #88

2022-05-13 17:57 UTC, martinjonsson01 requested changes
Great work! 

The main thing I want you to take a look at is the endpoint URL, the rest are nits and suggestions.

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Application/Contracts/IRecentContractRepository.cs
> +    void RemoveRecent(RecentlyViewedContract contractToRemove);
nit:
You don't need the `Recent` suffixes on these methods, because imagine the following code:
```csharp
var recentContractRepo = new RecentContractRepository();
recentContractRepo.AddRecent(recentContract);
```
vs
```csharp
var recentContractRepo = new RecentContractRepository();
recentContractRepo.Add(recentContract);
```

It gets very superfluous very quickly when putting the same suffix or prefix everywhere when it's already clear.

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Application/Contracts/RecentContractService.cs
>  public class RecentContractService : IRecentContractService
nit:
It's best to name implementing classes a lot more specifically than the interface they're implementing. This isn't just a generic recent contracts service, this is one that limits the amount of recent contracts to a specific number.

So I'd rename it (even though it doesn't look like you gave it this name) to something like `LimitedRecentContractService`.

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +                        <div class="d-flex flex-wrap justify-content-center">
nit:
```suggestion
                    <div class="d-flex flex-wrap justify-content-center">
```

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    public void ShowRecentContracts(bool shouldShow)
nit:
The way this method is named makes it sound like it's a void method, since it's a command rather than a configurer.

And anyway, should't you just make the property `ShouldShowRecent` into an actual public property that can be set from the outside, instead? That way this method is entirely unnecessary and you don't have to explicitly call `StateHasChanged`.

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    }
nit:
Instead of getter methods like this (which is very Java-like), you should use get-only auto-properties!

E.g.
```csharp
private string FetchUrl => BaseUrl + _session.Username;
```

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Domain/Contracts/Contract.cs
> +﻿using Domain.Users;
Is this necessary?

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Domain/Contracts/RecentlyViewedContract.cs
> +    /// Creates a instance of a recently viewed contract with the current time and contract id.
nit:
```suggestion
    /// Creates an instance of a recently viewed contract with the current time and contract id.
```

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Domain/Contracts/RecentlyViewedContract.cs
> +    /// Gets the viewers id.
nit:
```suggestion
    /// Gets the viewer's id.
```

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Domain/Users/User.cs
> +    /// Gets the most recently view contracts by the user.
nit:
```suggestion
    /// Gets the most recently viewed contracts.
```

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFDatabaseContext.cs
> +    /// <inheritdoc />
🙏

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFRecentContractRepository.cs
> +    private User GetUserByUserName(string username)
nit:
`GetUserByUserName` -> `GetUserByName`

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFRecentContractRepository.cs
> +        User user = Users.Include(user => user.RecentlyViewContracts).First(user => user.Name == username);
By using `.First()` here you'll throw an exception if there isn't a user that matches. You should instead 1) catch it and throw a user not found exception, or 2) use `.FirstOrDefault()` and if the returned value is null throw a user not found exception.

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Server/Controllers/ContractsController.cs
> +    [HttpGet("recent/{username}")]
This endpoint URL is incorrectly structured. It should be hierarchical, in descending order of how specific it is.

Right now we'll be calling `api/v1/contracts/recent/{username}` which makes it seem like a contract *has recent users*. This also puts the user last, which makes it seem like the user is a property of recent.

What we should be calling instead is `api/v1/users/{username}/recent-contracts` which shows that it's *users who have recent contracts*. This puts recents last which illustrates that recents are a property of the user.

2022-05-13 17:57 UTC, martinjonsson01 commented on src/Server/Controllers/ContractsController.cs
> +    [HttpPost("recent/{username}")]
Same here as above.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +    public void Size_ReturnsTheExpectedAmount()
nit:
```suggestion
    public void Size_ReturnsOne_WhenThereIsOnlyOneRecentContract()
```

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +    private const string UserId = "123";
nit:
It can get confusing if we have both `User.Id` and we start calling the property `User.Name` "UserId", so since this is referring to the name it should be called `UserName`.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +    }
This test isn't testing that it `ShouldDequeueTheOldestContract` as it says in the name, what it's actually testing is that it removes *any* contract. So you should either update the name or change the assertion to be more specific.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +    public void AddRecent_ShouldNotDequeueTheOldestContract_WhenAddingAnAlreadyAddedContract()
Same here as above, it should say
```suggestion
    public void AddRecent_ShouldNotRemoveAnyRecentContract_WhenAddingAnAlreadyAddedContract()
```

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +        var recent3 = new RecentlyViewedContract(contract3.Id, new User().Id);
Does this test assume that the system isn't too fast and creates these three at exactly the same time? 

That feels kind of iffy, but I suppose if you've never had it fail a single time then it should be robust enough to work.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/Admin/AdminPageTests.cs
> +        cut.Find(".loading-indicator").TextContent.Should().BeEquivalentTo("Laddar...");
🙌

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +    public void AddRecent_AddsTheContractCorrectly()
nit:
Naming tests by saying that things "should be done correctly" is very vague and not very helpful when they fail. If I see a red test that says `AddRecent_AddsTheContractCorrectly` then I have very little idea about what could have gone wrong. 

Now if you name it something like `FetchRecentContracts_KeepsIdIntact_WhenAddedWithId`, then it's a lot more easy to understand what's being tested and what could have gone wrong.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +    public void AddRecent_ReAddingAnExistingContractUpdatesTheTimeCorrectly()
nit:
It's not a hard rule that you have to append the name of the method under test, you don't have to force it in like this. 

```suggestion
    public void AddingContract_UpdatesTheTime_WhenContractAlreadyExists()
```

That way you can split it up into a very clear three-part structure which tells the reader `WhatIsBeingTested_WhatIsExpectedToHappen_UnderWhichConditions`.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +        _cut.AddRecent(user1.Name, contract1);
nit:
This line isn't what's being tested, it's part of the setup needed to run the test, so it's a part of the `// Arrange`.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +    public void RemoveRecent_RemovesCorrectContract()
nit:
Same here as the first comment in this file, you shouldn't just say "Does the correct thing", you should specify what correct means:
```suggestion
    public void RemoveRecent_RemovesSpecifiedContract_WhenThereAreMultipleRecents()
```

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +    public void RemoveContract_RemovesAllContractFromAllUser()
nit:
```suggestion
    public void Removing_RemovesRecentContractFromMultipleUsers_WhenMultipleUsersHaveViewedItRecently()
```

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +        _ = _context.RecentlyViewedContracts.Find(contract1.Id, user1.Id);
Is this line necessary in order to make the context aware of the recent contracts, so that it is able to cascade delete them? I would have thought the database would keep track of this without the need for them being active in the context, but maybe we didn't configure the migration like that.

2022-05-13 17:57 UTC, martinjonsson01 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +    public void RemoveContract_DoesNotChangeRecentlyViewedForUser_WhenRecentlyViewedDoesNotContainContract()
perfect naming 😍

2022-05-15 11:03 UTC, Matte02 commented on src/Application/Contracts/IRecentContractRepository.cs
> +    /// <param name="contract">Possible new recent contract.</param>
🤔

2022-05-15 11:04 UTC, Matte02 commented on src/Application/Contracts/RecentContractService.cs
> +                          throw new ContractDoesNotExistException());
🙌

2022-05-15 11:13 UTC, Matte02 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    public void ShowRecentContracts(bool shouldShow)
Sadly it doesn't work like that, changing the property doesn't cause it to change what's displayed.

2022-05-15 11:15 UTC, Matte02 commented on src/Domain/Contracts/Contract.cs
> +﻿using Domain.Users;
Nope, it wasn't. Leftovers from trying different methods for the database relationships. I kind of thought our formatter would remove unused dependencies.

2022-05-15 11:16 UTC, Matte02 commented on src/Infrastructure/Databases/EFDatabaseContext.cs
> +    /// <inheritdoc />
🙏

2022-05-15 11:20 UTC, Matte02 commented on src/Server/Controllers/ContractsController.cs
> +    [HttpGet("recent/{username}")]
Should this be moved to the `UserController` as well then? Or should it stay in `ContractsController`?

2022-05-15 11:30 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    public void ShowRecentContracts(bool shouldShow)
That's exactly what properties should do, are you sure that it's because of the property that it's not re-rendering?

If that's the case, you should still rewrite it as a property, but with (if it's really necessary) an explicit setter:
```csharp
    private bool _shouldShowRecent = true;
    private bool ShouldShowRecent
    {
        get => _shouldShowRecent;
        set
        {
            _shouldShowRecent = value;
            StateHasChanged();
        }
    }
```

2022-05-15 11:33 UTC, martinjonsson01 commented on src/Server/Controllers/ContractsController.cs
> +    [HttpGet("recent/{username}")]
For the sake of separation of concerns, it might be cleaner to keep the recents-stuff separate from the rest. 

So I'd try putting it in a `RecentsController` just like @pkasinski did in https://github.com/martinjonsson01/contract-portal/blob/d38d743c3fb8182dded89c9e91c23343d81b102b/src/Server/Controllers/FavoritesController.cs.

2022-05-15 12:23 UTC, Matte02 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    public void ShowRecentContracts(bool shouldShow)
I'm pretty sure it is, since this isn't working:
```csharp
   /// <summary>
    /// Gets or sets whether recent contracts should be displayed or not.
    /// </summary>
    public bool ShouldShowRecent { get; set; } = true;
```
![image](https://user-images.githubusercontent.com/55716109/168472711-d3e812c4-c87b-432a-8e67-e7d53bd35e30.png)


while this is working: 
```csharp
  private bool _shouldShowRecent = true;

    /// <summary>
    /// Gets or sets whether recent contracts should be displayed or not.
    /// </summary>
    public bool ShouldShowRecent
    {
        get => _shouldShowRecent;
        set
        {
            _shouldShowRecent = value;
            StateHasChanged();
        }
    }
```
![image](https://user-images.githubusercontent.com/55716109/168472690-d6f10d08-9887-40f2-9edd-b64508e8e099.png)

2022-05-15 12:25 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    public void ShowRecentContracts(bool shouldShow)
That's weird, but fair enough!

2022-05-15 12:28 UTC, martinjonsson01 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +        var recent3 = new RecentlyViewedContract(contract3.Id, new User().Id);
The only way to make the test more robust (if it's a problem) is to add an optional constructor parameter that lets you specify the time it was recently viewed, so the tests could mock fake times between the contract views.

Maybe it's not worth the hassle, given that the tests aren't failing randomly 😛

2022-05-15 12:31 UTC, Matte02 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +        var recent3 = new RecentlyViewedContract(contract3.Id, new User().Id);
This has been working every time for me, I could add a delay just for safety if you want.

2022-05-15 12:33 UTC, martinjonsson01 commented on tests/Application.Tests/Contracts/RecentContractServiceTests.cs
> +        var recent3 = new RecentlyViewedContract(contract3.Id, new User().Id);
Nonono, we *don't* want to add artifical delays like `Thread.Sleep(100);`, that just artificially slows down the tests for no good reason. 

If we want to make the tests more robust then the way to do it is to fake a time separation, by creating fake `DateTime` instances with artificial delays. But since you're saying that it's not a problem, then you can probably leave it as-is.

2022-05-15 12:35 UTC, Matte02 commented on tests/Infrastructure.Tests/Contracts/RecentContractRepositoryTests.cs
> +        _ = _context.RecentlyViewedContracts.Find(contract1.Id, user1.Id);
Good catch, it was a leftover from testing different solutions.

2022-05-15 13:38 UTC, martinjonsson01 approved these changes
lgtm 👍

2022-05-15 13:38 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    private string FetchUrl => BaseUrl + _session.Username + UrlRecentSuffix;
Very nice composition of the fetch url, makes it very readable! 👍

2022-05-15 13:38 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
Just to double check that this isn't a mistake from the merge conflicts, is this really supposed to be here?
IIRC this table ("ContractUsers") was dropped in one of the migrations we created for recent contracts.

2022-05-15 13:38 UTC, martinjonsson01 commented on src/Server/Controllers/RecentsController.cs
> +    }
nit:
Since you're not returning any custom HTTP-codes or any return result at all, really, you can make the method void and have it implicitly return 200 OK.

```suggestion
    /// <summary>
    /// Adds a contract as recently viewed.
    /// </summary>
    /// <param name="username">The logged in user.</param>
    /// <param name="contract">The contract to add.</param>
    [HttpPost]
    public void Add(string username, Contract contract)
    {
        _recent.Add(username, contract);
    }
```

2022-05-15 13:38 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/RecentlyViewedTests.cs
> +        MockHttp.When("/api/v1/users//recents").RespondJson(Array.Empty<object>());
This URL is incorrect, and caused by a bug that is solved in #146. Whichever one of the these two PRs that gets merged first needs to update these tests to mock the correct endpoint, but I understand that you can't do that right now since the fixes aren't implemented in this branch.

2022-05-15 13:38 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/RecentlyViewedTests.cs
> +        MockHttp.When("/api/v1/users//recents").RespondJson(new[] { contract, });
This URL is incorrect, and caused by a bug that is solved in #146. Whichever one of the these two PRs that gets merged first needs to update these tests to mock the correct endpoint, but I understand that you can't do that right now since the fixes aren't implemented in this branch.

2022-05-15 13:39 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
And it looks like the CI is failing because of this as well, you should take a look at what the snapshot should really contain.

2022-05-15 14:16 UTC, Matte02 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
I might be wrong but I'm pretty sure those came from master, with show personalized favorites.

2022-05-15 14:17 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
Yeah, it came from master but on this branch we removed that table, right?

2022-05-15 14:17 UTC, Matte02 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
I believe the problem is that RecentlyViewed also wants to create a ContractUsers table, and there can't be 2 tables with the same name.

2022-05-15 14:19 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
No, in this branch we're using a table for `RecentlyViewedContracts` instead. The `ContractUsers` table was the old way, when the recent contracts were global, IIRC

2022-05-15 14:21 UTC, Matte02 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
![image](https://user-images.githubusercontent.com/55716109/168477566-b57da4d7-47b7-4e65-8a69-2636758dd7fc.png)
![image](https://user-images.githubusercontent.com/55716109/168477581-cb1a9192-72a9-4a22-9264-aa4bfab52bca.png)
These are from master

2022-05-15 14:21 UTC, Matte02 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
https://github.com/martinjonsson01/contract-portal/blob/master/src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs

2022-05-15 14:23 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
Hmm, yeah it seems you're right they're used by favorites. (I wasn't arguing that they're not from master, I was arguing that they weren't used by favorites and were therefore redundant)

Then the problem is that in one of the migrations we made we explicitly drop the ContractUsers table somewhere, so if you remove that then that could solve it.

2022-05-15 14:35 UTC, Matte02 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
I'll take a look at it whenever I get time (Monday, Tuesday, or Wednesday). Tried changing the migration but didn't manage to get it to work, probably missed something somewhere.

2022-05-15 14:36 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
If this is all that remains on this PR then I could take a look now and see if I find anything

2022-05-15 15:19 UTC, martinjonsson01 commented on src/Infrastructure/Migrations/EFDatabaseContextModelSnapshot.cs
> +                });
I solved it, you were right that the `ContractUser` table was being used by the favorites, but surprisingly (and I think this was the issue) it was also the name of the table used for recents. Maybe not so surprising since they both associated a user with a contract. 

I solved it by giving the tables more specific names, so now they're named after favorites and recents instead.

2022-05-17 07:47 UTC, JacobBredin approved these changes
LGTM, well done 🥳

2022-05-17 07:47 UTC, JacobBredin commented on src/Infrastructure/Databases/EFDatabaseContext.cs
> +                        .UsingEntity(join => join.ToTable("UserFavoriteContracts"));
Sorry about that 😓

2022-05-17 07:47 UTC, JacobBredin commented on src/Domain/Contracts/RecentlyViewedContract.cs
> +public class RecentlyViewedContract
Nice 👍

2022-05-17 08:08 UTC, JacobBredin requested changes
I found a bug while checking the code for a second time

2022-05-17 08:08 UTC, JacobBredin commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    private string FetchUrl => BaseUrl + _session.Username + UrlRecentSuffix;
This will not work if _session.Username is null, because the url `/api/v1/users//recents` will be called. This scenario happens if no one is logged in and the contract page is visited.

2022-05-17 10:32 UTC, Matte02 commented on src/Client/Pages/Contracts/RecentlyViewed.razor
> +    private string FetchUrl => BaseUrl + _session.Username + UrlRecentSuffix;
Good catch! Should be fixed now, take a look and see if you approve of the solution.

2022-05-17 10:52 UTC, martinjonsson01 commented on src/Application/Contracts/LimitedRecentContractService.cs
> +        }
Why are you catching this here and doing nothing? I think it was better the way it was before, because if the caller is trying to add a recent contract to a user that does not exist then that warrants an exception being thrown to them.

2022-05-17 11:01 UTC, Matte02 commented on src/Application/Contracts/LimitedRecentContractService.cs
> +        }
Whops, moving the catch to the controller

2022-05-17 11:04 UTC, martinjonsson01 commented on src/Application/Contracts/LimitedRecentContractService.cs
> +        }
Great, that's much better 👍

2022-05-17 11:32 UTC, JacobBredin approved these changes
Nicely done 🥳

2022-05-17 12:03 UTC, merged