20 editing users
martinjonsson01/contract-portal pull request #145
Opened 2022-05-13 17:28 UTC by Gigset

## Summary
Enables editing of already existing users, and storing their new values in the database.

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #20-editing-users

https://user-images.githubusercontent.com/73949651/168336488-9efe30c3-a440-4c4c-a92f-b2430ff7245d.mp4

2022-05-13 18:14 UTC, martinjonsson01 requested changes
Looking good, I've got a few things that I would like you to take a look at.

And it seems like the tests aren't compiling now that you've renamed the `Add` method to `AddOrUpdate` and you've added a new parameter to the `Create` method.

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Application/Users/UserService.cs
> +        return _repo.FetchUser(id) ?? throw new UserDoesNotExistException();
Great use of the null-coalescing operator 🤩

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserForm.razor
> +<EditForm Model="@_user" OnSubmit="OnSubmit">
nit:
A callback that is named after the event it handles isn't very readable, `OnSubmit="OnSubmit"` doesn't tell me a lot, but e.g. `OnSubmit="ConvertAndUploadUser"` does.

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserForm.razor
> +    public async Task EditUsersAsync(User user)
nit:
```suggestion
    public async Task EditUserAsync(User user)
```

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserForm.razor
> +    }
If you copied this over from `ContractForm` just to make them match, that isn't necessary. The reason for why `ContractForm` has all this extra rendering logic is because of the file uploads, which doesn't exist here in `UserForm`. So you can remove all the stuff with `_shouldRender`, if you didn't add it for some other reason?

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserForm.razor
> +    // Make sure date is in UTC.
nit:
```suggestion
        // Make sure date is in UTC.
```

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserTable.razor
> +    public void AddOrUpdate(User user)
nit:
You should update the documentation to reflect the new behavior.

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserTable.razor
> +    // can not be null when remove button is pressed.
nit:
😭 
```suggestion
            // Using null forgiving operator because because _users
            // can not be null when remove button is pressed.
```

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFUserRepository.cs
> +    /// <param name="updatedUser">Documentation.</param>
Documentation?

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFUserRepository.cs
> +    /// <param name="updatedUser">Documentation.</param>
🤖

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFUserRepository.cs
> +    /// Summary.
Summary?

🤖

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFUserRepository.cs
> +    /// <param name="id">id.</param>
Id? 🤖

2022-05-13 18:14 UTC, martinjonsson01 commented on src/Infrastructure/Databases/EFUserRepository.cs
> +    /// <returns>Returnable.</returns>
Re tur nable? 🤖

2022-05-13 18:17 UTC, martinjonsson01 requested changes

2022-05-13 18:17 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserForm.razor
> +        _user = user;
This doesn't work quite as expected when it comes to the password field, as the encrypted value is input into the password box. Since it's impossible to decrypt this password, and we don't want the encrypted value to be modified, we should instead put an empty string in its stead, so that the admin has to set a new password (or re-type the old one).

2022-05-13 19:17 UTC, Gigset commented on src/Infrastructure/Databases/EFUserRepository.cs
> +    /// <param name="updatedUser">Documentation.</param>
Documentation.

2022-05-15 10:50 UTC, Matte02 approved these changes
Lgtm!

2022-05-15 11:39 UTC, martinjonsson01 approved these changes
lgtm 👍

2022-05-15 12:51 UTC, merged