24 show contracts in admin panel
martinjonsson01/contract-portal pull request #36
Opened 2022-04-07 14:15 UTC by Matte02

## Summary
Adds contract list to the admin page. 
![image](https://user-images.githubusercontent.com/55716109/162220036-55cadaa6-519b-4c32-9c5b-ab3d8d08d246.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [ ] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.

Closes #24

2022-04-07 16:59 UTC, JacobBredin approved these changes
Lgtm! One sort of related question I want an answer to

2022-04-07 16:59 UTC, JacobBredin commented on tests/Client.Tests/Pages/AdminPageTests.cs
> +        _mockHttp.When("/api/v1/Contracts/All").RespondJson(fakeContracts);
Seems a bit unflexable that the route is hardcoded, but I guess it is just temporary? I'm just mentioning it since I haven't noticed it before.

2022-04-07 18:05 UTC, martinjonsson01 requested changes
Looks good, I mainly want you to reduce code duplication in the tests.

2022-04-07 18:05 UTC, martinjonsson01 commented on src/Client/Pages/Admin.razor
> +
We spoke about putting our code not directly in the admin page, instead in a separate component, to avoid merge conflicts. Is there a reason you didn't?

2022-04-07 18:05 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/AdminPageTests.cs
> +    }
Now that we have two test classes using the exact same boilerplate-code, we should probably extract the common parts into a superclass. Something like `UITestFixture` and have `AdminPageTests` and `ContractPageTests` inherit from it.

2022-04-07 18:05 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/AdminPageTests.cs
> +        _mockHttp.When("/api/v1/Contracts/All").RespondJson(fakeContracts);
I'm not sure how else we would do it? 

We could possibly use environment variables, but I'm not sure it's worth the hassle as URLs are supposed to be stable and unchanging.

2022-04-07 18:05 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/ContractListItemTests.cs
> +    private readonly TestContext _context;
Same here, this should also inherit from the `UITestFixture`.

2022-04-07 18:09 UTC, ellsib commented on src/Client/Pages/Admin.razor
> +        <em>Loading...</em>
More appropriate to have something like "You have no contracts here at the moment"?

2022-04-07 18:09 UTC, ellsib commented on src/Client/Pages/Admin.razor
> +        <em>Loading...</em>
(this is also to try out the review process in Github :))

2022-04-08 08:39 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin.razor
> +
Either I was not a part of the dicussion or simply forgot it. 

But @Matte02 did ask if would be better to make this its own component, and I said it was not. My reasoning was that the code is not reused anywhere _yet_ and the file is not massive. 

Either way I do not think we will avoid merge conflicts, it will just be smaller. And is it a valid reason to make something a component to make merge conflicts easier?

2022-04-08 08:39 UTC, jonathan-lindqvist commented on tests/Client.Tests/Pages/AdminPageTests.cs
> +    }
Will look into it 😄

2022-04-08 08:39 UTC, jonathan-lindqvist commented on tests/Client.Tests/Pages/AdminPageTests.cs
> +        _mockHttp.When("/api/v1/Contracts/All").RespondJson(fakeContracts);
The component we are testing is using that endpoint, therefore we need it. Now it could be put into a string variable but is it worth it when its only used once?

2022-04-08 08:39 UTC, jonathan-lindqvist commented on tests/Client.Tests/Pages/ContractListItemTests.cs
> +    private readonly TestContext _context;
👍

2022-04-08 08:39 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin.razor
> +        <em>Loading...</em>
Yeah, a more descriptive message would be better 👍

2022-04-08 08:47 UTC, martinjonsson01 commented on src/Client/Pages/Admin.razor
> +
Yeah, on your end it's very simple right now. The idea was to preempt the creation of a huge admin-page that would inevitably have to be broken out into separate components to make it readable. 

While it's true that it's not worth it to break them out into components for code reuse, it's also true that it's much better Separation of Concern to have each part of the admin-page in a separate component. E.g. when I want to modify how the list of contracts are shown on the admin page, I shouldn't have to trod through a bunch of code related to creating and editing contracts since those are separate concerns. 

Avoiding large merge conflicts is a nice benefit of following SoC, but it's true that we probably shouldn't use it as our main motivator. (But I would still argue that it's much easier to handle a merge conflict between two lines of code in the admin-page for the two added components, rather than two entirely different component-implementations, so that point still stands.)

2022-04-08 11:09 UTC, JacobBredin commented on tests/Client.Tests/Pages/AdminPageTests.cs
> +        _mockHttp.When("/api/v1/Contracts/All").RespondJson(fakeContracts);
No nothing we need to change now, it can stay.  And I guess they are supposed to be stable, but it still seems like it could lead to a lot of annoying shotgun surgery later.

2022-04-08 12:19 UTC, Matte02 commented on src/Client/Pages/Admin.razor
> +        <em>Loading...</em>
This is only shown when the client is waiting for contracts from the application. This is not shown when there are no contracts.

2022-04-08 12:52 UTC, martinjonsson01 approved these changes
LGTM 👍

2022-04-08 12:52 UTC, martinjonsson01 commented on tests/Client.Tests/Pages/AdminPageTests.cs
> +        // Arrange
Nice, very clean tests! 🤩

2022-04-08 13:48 UTC, merged