17 adding contract data from admin page
martinjonsson01/contract-portal pull request #39
Opened 2022-04-09 14:42 UTC by martinjonsson01

## Summary
Adds an input form on the admin page, allowing admins to create new contracts.

NOTE: this PR contains no error-handling in the UI, but it's not something we should ignore since it's important for usability. I suggest we create a new story about adding this.
(I would have included it in this PR, but it's already a bit big so I thought it'd be better to err on the side of not-humongous-PRs.)

![chrome_KsEUwHOwxV](https://user-images.githubusercontent.com/12572888/162578953-ceec2e77-e149-4659-830f-23ffd7eb221c.gif)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #17

2022-04-09 17:38 UTC, pkasinski approved these changes
LGTM

2022-04-10 08:47 UTC, ellsib approved these changes
Bra jobbat! Har läst igenom allt och la ett par kommentarer som du kan kika på. Tamás kommer strax med en review också.

2022-04-10 08:47 UTC, ellsib commented on src/Client/Pages/Admin/ContractForm.razor
> +    /// <summary>
Hade möjligtvis kunna vara någon mer dokumentation på specifika delar i dokumentet, men metodnamnen känns deskriptiva så är nog inget måste.

2022-04-10 08:47 UTC, ellsib commented on src/Client/Pages/Admin/ContractForm.razor
> +    /// <summary>
När vi lämnar över projektet hade det tex varit användbart med dokumentation på vad koden _gör_ istället för bara _när_ det anropas. :)

2022-04-10 08:47 UTC, ellsib commented on src/Application/Exceptions/IdentifierAlreadyTakenException.cs
> +/// The identifier was already taken.
Se Tamás kommentar.

2022-04-10 08:47 UTC, ellsib commented on tests/Application.Tests/Contracts/ContractServiceTests.cs
>      public void FetchAllContracts_ReturnsAllContractsInTheDatabase()
Bra namngivning! (Gäller generellt på tester)

2022-04-10 08:51 UTC, XwayTomy approved these changes
Snyggt jobbat!

2022-04-10 08:51 UTC, XwayTomy commented on src/Application/Exceptions/IdentifierAlreadyTakenException.cs
> +        : base(message, innerException)
Vad är fördelarna med att ha tre olika konstruktorer?

2022-04-10 08:51 UTC, XwayTomy commented on src/Application/Images/IImageRepository.cs
> +    /// <returns>The identifier of the stored image.</returns>
Snygg dokumentation!

2022-04-10 08:51 UTC, XwayTomy commented on src/Domain/Contracts/Contract.cs
>      public string ImagePath { get; set; } = "images/sj.png";
Varför just SJ när allt annat är generellt?

2022-04-10 10:34 UTC, jonathan-lindqvist requested changes
Overall really neat, just left some nits and questions 👍

2022-04-10 10:34 UTC, jonathan-lindqvist commented on .gitignore
> +**/unsafe_uploads
😬

2022-04-10 10:34 UTC, jonathan-lindqvist commented on src/Application/Images/InvalidImageException.cs
> +        : base("Image is invalid.")
What makes an image invalid? Is this if someone tries ti upload a pdf instread of apng?

2022-04-10 10:34 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/AdminPage.razor
> +    private ContractList _contractList = null!;
Not 100% sure what `null!` does, but seems we should be careful with using it as it seems to be the source of a lot of bugs? Also is it standard practice to define variables below methods? Eitherway it doesn't seem to matter so it is a NIT :)

2022-04-10 10:34 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/ContractForm.razor
> +        <InputText id="title" class="form-control" placeholder="Skriv titel här..." @bind-Value="@_contract.Name"/>
NIT: I dont remember the design patterns exctly for forms but I recall that examples could be given in the placeholder. Though it might not be as applicable here, especially in the description.

2022-04-10 10:34 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/ContractForm.razor
> +    protected override bool ShouldRender()
Is it being used somewhere outside of this? Or can we just use our variable?

2022-04-10 10:34 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/ContractForm.razor
> +        const long maxFileSize = 1024 * 1024 * 100;
NIT: magic numbers

2022-04-10 10:34 UTC, jonathan-lindqvist commented on src/Application/Contracts/IContractRepository.cs
> +    public ICollection<Contract> Contracts { get; }
Could this be returned as readonly? Because we don't want to add it directly to the collection, it should go through the database first.

2022-04-10 10:38 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +    /// <summary>
That's fair, but actually this property here is an `EventCallback<T>` which means it's an event that this component is able to fire. *What* happens when the event is fired is not defined inside of this component, by design. *When* the event fires is the only thing this component is responsible for.

2022-04-10 10:40 UTC, martinjonsson01 commented on src/Application/Exceptions/IdentifierAlreadyTakenException.cs
> +        : base(message, innerException)
I wondered this myself, because originally I only wrote it with one. The reason I added more was because of [this](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1032) style error, which basically states that all existing exceptions in C# have these three different ways of being constructed, so if I make a new exception which doesn't follow this standard then that will surprise developers who are used to this fact.

2022-04-10 10:42 UTC, martinjonsson01 commented on src/Domain/Contracts/Contract.cs
>      public string ImagePath { get; set; } = "images/sj.png";
This line wasn't added in this PR, so isn't really relevant, but it's a good question nonetheless and I believe the answer is that it's just a default-value, a placeholder. It's better to have *some* value rather than none, but you're right it should probably be an "no image found" image or something similar.

2022-04-10 10:42 UTC, martinjonsson01 commented on .gitignore
> +**/unsafe_uploads
Yeah, going all the way security-wise in this PR felt out-of-scope (as it was already getting a bit big). We should make another user story about strengthening the security.

2022-04-10 10:44 UTC, martinjonsson01 commented on src/Application/Images/InvalidImageException.cs
> +        : base("Image is invalid.")
It's not up to the exception to specify this, it's up to the throwers of the exception (that's why I didn't specify it in the documentation here), but it's a reasonable question to ask. 

Currently it's exactly like you say, anything with a MIME-type of a non-image is treated as invalid, but in the future we should probably also treat images that are too big in size as invalid, as well.

2022-04-10 10:47 UTC, martinjonsson01 commented on src/Client/Pages/Admin/AdminPage.razor
> +    private ContractList _contractList = null!;
It's the null-forgiving operator. Normally, you're not allowed to assign a `null` value to a non-nullable reference type (I declared `ContractList` and not `ContractList?`), but with this it allows you to do it. It's true that it is an operator that should rarely be used, because it ruins the point of the nullability-system. 

In this case I used it instead of declaring the type as nullable because the Blazor runtime *will always* assign it a value since I've associated it with a `@ref=""` tag on the component above. The C# compiler doesn't recognize this as it's a custom feature of Blazor, so I had to forgive the null value. 

I *could* have declared it as nullable instead, but that would only obscure the intention behind the field. The intention here is to show that while the compiler believes there may be a null-value, I *know* that there won't, so I'll allow it.

2022-04-10 10:48 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +        <InputText id="title" class="form-control" placeholder="Skriv titel här..." @bind-Value="@_contract.Name"/>
Good point, do you have any ideas for examples? It's a bit hard to come up with any examples without explicitly referring to actual companies and such. At least for the title-input.

2022-04-10 10:50 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +    protected override bool ShouldRender()
This is an overriden method, which you might've missed. It's part of the [`ComponentBase` base class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.shouldrender?view=aspnetcore-6.0#microsoft-aspnetcore-components-componentbase-shouldrender) and allows us to tell the runtime whether a component should re-render or not.

2022-04-10 10:50 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +    protected override bool ShouldRender()
Either that, or I've misunderstood your point

2022-04-10 10:59 UTC, martinjonsson01 commented on src/Application/Contracts/IContractRepository.cs
> +    public ICollection<Contract> Contracts { get; }
Good point. I recalled (incorrectly) that the `DbSet<T>` class that we'll use to implement the repository in the future with [EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli) actually implemented `ICollection<T>` so we could directly access and query it with no dependency issues, but looking at it now it seems like it doesn't. 

Instead, we should completely hide the collection and have very specific methods for manipulating data, I'll set that up now.

2022-04-10 11:12 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +        <InputText id="title" class="form-control" placeholder="Skriv titel här..." @bind-Value="@_contract.Name"/>
I added some vague examples

2022-04-10 11:19 UTC, martinjonsson01 commented on src/Client/Pages/Admin/AdminPage.razor
> +    private ContractList _contractList = null!;
And no, just like in Java the member fields should be placed above the methods and constructors. It's too bad that our style checker doesn't seem to handle `.razor` files too well otherwise it would have caught that. Anyway, it's fixed now.

2022-04-10 11:23 UTC, jonathan-lindqvist commented on .gitignore
> +**/unsafe_uploads
👍

2022-04-10 11:23 UTC, jonathan-lindqvist commented on src/Application/Images/InvalidImageException.cs
> +        : base("Image is invalid.")
👍

2022-04-10 11:24 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/AdminPage.razor
> +    private ContractList _contractList = null!;
👍

2022-04-10 11:24 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/ContractForm.razor
> +    protected override bool ShouldRender()
Aaah, I see then its 👍

2022-04-10 11:25 UTC, jonathan-lindqvist commented on src/Application/Contracts/IContractRepository.cs
> +    public ICollection<Contract> Contracts { get; }
👍

2022-04-10 11:26 UTC, jonathan-lindqvist requested changes
LGTM 👍

2022-04-10 11:26 UTC, jonathan-lindqvist approved these changes
LGTM (approved) 👍

2022-04-10 11:52 UTC, merged