43 implement a global style sheet
martinjonsson01/contract-portal pull request #49
Opened 2022-04-12 09:23 UTC by pkasinski

## Summary
Changes the style sheet to create a uniform styling of the website.

![Screen Shot 2022-04-12 at 11 16 52](https://user-images.githubusercontent.com/83813240/162927252-ee5ff5c4-4b8a-4f28-a929-925a5259b696.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [ ] The code has (at least) 80% branch test coverage.
- [ ] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #43

2022-04-12 09:38 UTC, martinjonsson01 requested changes
Nice! 

Just a minor detail about the headings.

2022-04-12 09:38 UTC, martinjonsson01 commented on src/Client/wwwroot/css/app.css
> +}
It seems like [Prodigo.se](https://prodigo.se/) uses Merriweather only for `h1, h2` and Roboto for `h3, h4, h5, h6`. At least that's what I found, maybe you found something else?

2022-04-12 09:41 UTC, martinjonsson01 commented on src/Client/wwwroot/css/app.css
> +}
Also, no styling for `h3`?  Maybe they didn't have any of that type of header on their website, but I think it's better if we have the option to use this inbetween-size, so could you maybe give it a size inbetween `h4` and `h2`?

2022-04-12 10:05 UTC, pkasinski commented on src/Client/wwwroot/css/app.css
> +}
`h3` is not currently used on their website, but I can add it.

2022-04-12 10:19 UTC, martinjonsson01 approved these changes
lgtm 👍

2022-04-12 12:23 UTC, XwayTomy approved these changes
LGTM!

2022-04-12 12:26 UTC, jonathan-lindqvist requested changes
Just left one request because it might cause some problems. Otherwise nicely done 👍

2022-04-12 12:51 UTC, pkasinski commented on src/Client/wwwroot/css/app.css
> +}
These values are from prodigo.se. Do you think we should use different units?

2022-04-12 13:03 UTC, martinjonsson01 commented on src/Client/wwwroot/css/app.css
> +}
We could use `rem` units instead, they're defined (at 100% scaling) as 16px so just divide the current numbers by 16 and replace the unit with `rem`.

2022-04-13 08:51 UTC, jonathan-lindqvist approved these changes
LGTM!

2022-04-13 09:18 UTC, merged