45 recently viewed contracts
martinjonsson01/contract-portal pull request #50
Opened 2022-04-12 12:16 UTC by jonathan-lindqvist

## Summary
If a user clicks on a contract it will be seen as recently viewed and displayed as such on the contract page.

## Definition of done
- [x] All acceptance criteria are completed.
- [ ] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #45

2022-04-12 16:01 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Admin/AdminPageTests.cs
> +        cut.Find("p em").TextContent.Should().BeEquivalentTo("Laddar...");
nit:
Hmm, I'm not sure I'm a fan of this. Not the fact that you updated the tests, since that's exactly what you should do when they start failing, but *the fact that you had to in the first place* is a bit worrying. It points to the fact that our tests are being coupled to our implementations so that the most minor change like swapping out a word causes the tests to fail. 

I'm actually not sure how we could solve that in this case, any ideas? (btw, not saying you should fix it in this PR, just bringing it up for discussion)

Maybe if we were to start using `id`s and `class`es for everything instead of looking at the actual elements or text, that could possibly allow us to make any changes we want to the UI while still keeping the tests functioning.

2022-04-12 16:02 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/RecentlyViewdTests.cs
> +public class RecentlyViewdTests : UITestFixture
nit:
`Viewd` -> `Viewed`

2022-04-12 16:05 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Admin/AdminPageTests.cs
> +        cut.Find("p em").TextContent.Should().BeEquivalentTo("Laddar...");
(I realize that I'm slowing down the whole PR-process by bringing up discussion questions in the comments, but this is where you usually realize that there are issues to be discussed. Maybe we should decide on a common way for the team to handle these a bit more quickly, like maybe taking them up in the discord-thread instead?)

2022-04-13 08:55 UTC, jonathan-lindqvist commented on src/Application/Contracts/ContractService.cs
> +    }
Yeah, we should minimze the amount of data that is being sent from and to the server. So if we fetch all contracts just to discard all but 3-5 contracts seems unnecessary. 

One problem, how to we implement this into the database in the future. But I guess that question can wait till we actully implement one.

2022-04-13 08:56 UTC, jonathan-lindqvist commented on src/Client/Pages/ContractCard.razor
> +    public Contract? Contract { get; set; }
100% agree 😄

2022-04-13 09:17 UTC, jonathan-lindqvist commented on tests/Presentation.Tests/Client/Pages/Admin/AdminPageTests.cs
> +        cut.Find("p em").TextContent.Should().BeEquivalentTo("Laddar...");
I agree on all fronts. This should not happen, and this is where problems like this are caught! I will not fix this in this PR but we should 100% discuss this and I will also look into it

2022-04-13 09:25 UTC, martinjonsson01 commented on src/Application/Contracts/ContractService.cs
> +    }
Using EF Core we can use normal LINQ-statements to construct queries as if we were reading from a list of items, and then it'll optimize it into an SQL query that is suitable behind-the-scenes. 

But yeah, that's out of scope for this PR, so nothing to do here. 👍

2022-04-13 09:25 UTC, martinjonsson01 commented on src/Application/Contracts/IContractRepository.cs
> +    IEnumerable<Contract> Recent { get; }
Yeah, you can disregard this.

2022-04-13 09:28 UTC, jonathan-lindqvist commented on src/Client/Pages/ContractsPage.razor
> +        _recentlyViewed.ReRender();
Yeah, Im not super happy with the current implemntation, but I feel like it was one of the better options. Right now the logic for what contracts are recent are done on the backend, if we add the contract "locally" in the frontend it will need to the pretty much the exact same checks. 

But then again the current implemntation calls the server way to many times. 

And the backend logic will actully get moved to the database in the future so there will be no code duplication.

2022-04-13 09:32 UTC, martinjonsson01 commented on src/Client/Pages/ContractsPage.razor
> +        _recentlyViewed.ReRender();
Ah, that makes sense. Yeah, we don't want to duplicate logic like that. 

You could make it really basic and having the client just discard the oldest recently viewed contract and replacing it with the newly added one. That wouldn't require the same logic as in the backend, as you only have to account for the ones that have already been fetched and the newly added one.

You could also take advantage of our shared Application layer and have a common `FilterRecentContracts(List<Contract>)` method there that is called both by the server and the client. Then there'd be no code duplication and we'd be sure that they're always in sync. The difference would be that the server considers all contracts while the client only considers the ones it has already fetched + the one it recently viewed.

2022-04-13 09:48 UTC, JacobBredin requested changes
I've only looked at the functionality so far, but I found two bugs:

1. Deleted contracts are still visible in the Latest visited list.

2. The "last visited"-list shows contracts in reverse order that they were visited in. The latest is placed on the right most side, instead of to the left.

I'm going to do a deeper review later today, hopefully 😊

2022-04-13 11:22 UTC, martinjonsson01 approved these changes
lgtm 👍

2022-04-13 11:22 UTC, martinjonsson01 commented on src/Client/Pages/RecentlyViewed.razor
> +        // _recent = await _http.GetFromJsonAsync<Contract[]>("/api/v1/Contracts/Recent");
nit:
Forgotten comment?

2022-04-13 11:22 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/RecentlyViewdTests.cs
> +public class RecentlyViewedTests : UITestFixture
nit:
Looks like the file name is still `ViewdTests`?

2022-04-13 13:33 UTC, martinjonsson01 approved these changes
Very clean! 👍

2022-04-13 13:33 UTC, martinjonsson01 commented on src/Application/Contracts/IRecentContractService.cs
> +    /// Gets many recent contracts.
nit:
Should it be "Gets *how* many recent contracts there are"?

2022-04-13 13:33 UTC, martinjonsson01 commented on src/Application/Contracts/IRecentContractService.cs
> +    public int Size();
nit:
No need to declare `public` in interfaces.

2022-04-13 13:33 UTC, martinjonsson01 commented on src/Infrastructure/Contracts/FakeContractRepository.cs
> +        _recent.AddRecent(contract);
😍

2022-04-14 06:51 UTC, JacobBredin approved these changes
LGTM 👍🚢

2022-04-14 08:18 UTC, merged