30 Adding additional information to contracts
martinjonsson01/contract-portal pull request #52
Opened 2022-04-13 13:22 UTC by JacobBredin

## Summary
Additional fields for supplier information has been added. The contracts form has been extended to contain appropriate text fields and file upload buttons for each new field.

![image](https://user-images.githubusercontent.com/70701264/163189367-3962aee9-5dd9-48f0-b5f0-c133bab1e699.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #30

2022-04-13 13:29 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/ContractForm.razor
> +        <InputTextArea id="instructions" class="form-control" placeholder="T.ex. Prodigo" @bind-Value="@_contract.SupplierName"/>
I got a bit confused when just looking at the code, because I thought this was the same field as the first. 

Will these two fields be different? Should the contract be displayed as something else than the company name?

2022-04-13 13:47 UTC, martinjonsson01 requested changes
Looking good, just a few things need to be fixed.

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Application/Documents/IDocumentRepository.cs
> +    Task<string> StoreAsync(Stream imageStream);
Sussy documentation 👀

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Application/Documents/InvalidDocumentException.cs
> +/// </summary>
docs 👀

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +    <br />
+1

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +        <InputTextArea id="instructions" class="form-control" placeholder="T.ex. Prodigo" @bind-Value="@_contract.SupplierName"/>
The `for` and `id` values should not be "instructions" down here. It should be updated to something like "supplier-name".

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +        <InputFile id="image" class="form-control" OnChange="(e=> OnFileChosen(e, ref _additionalDocumentContent))"/>
We requested that they add the inspirational image, we use it in the details view.

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Infrastructure/Documents/DocumentVerifier.cs
> +        //// Allow MIME-types starting with image/ since all widely used image formats do.
Comment is no longer valid 👀

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Server/Controllers/DocumentsController.cs
> +public class DocumentsController : BaseApiController<DocumentsController>
docs 👀

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Server/Controllers/DocumentsController.cs
> +    public DocumentsController(ILogger<DocumentsController> logger, IDocumentRepository images)
docs and parameter name 👀

2022-04-13 13:47 UTC, martinjonsson01 commented on src/Server/Controllers/DocumentsController.cs
> +    public async Task<ActionResult<string>> UploadImageAsync()
docs and method name 👀

2022-04-13 14:06 UTC, JacobBredin commented on src/Client/Pages/Admin/ContractForm.razor
> +        <InputTextArea id="instructions" class="form-control" placeholder="T.ex. Prodigo" @bind-Value="@_contract.SupplierName"/>
copy paste bug 😔

2022-04-14 06:55 UTC, JacobBredin commented on src/Client/Pages/Admin/ContractForm.razor
> +    <br />
I've added divs around the two different sections for the contract and the supplier. I'm not completely sure if I did it the right way, please check.

2022-04-14 06:56 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractForm.razor
> +    </div>
FYI it's possible to put margin and padding on the elements themselves, no need for the extra divs! :) 

It's usually bad practice to introduce unnecessary divs into the markup, since it creates a lot of noise for the readers of the code.

2022-04-14 07:24 UTC, JacobBredin commented on src/Client/Pages/Admin/ContractForm.razor
> +    </div>
I tried to find a solution where you use gutters, but I guess putting margins on elements is simpler and makes it easier to read.

2022-04-14 08:27 UTC, jonathan-lindqvist approved these changes
Nice!

2022-04-14 09:51 UTC, martinjonsson01 approved these changes
lgtm 👍

2022-04-14 10:03 UTC, merged