46 favorite contracts
martinjonsson01/contract-portal pull request #73
Opened 2022-04-19 07:35 UTC by Matte02

## Summary
Adds a favorite button to each contract and shows all favorite marked contracts on the dashboard.
![image](https://user-images.githubusercontent.com/55716109/163950016-fc9c071e-588d-4512-a0c9-94390f3e1809.png)
![image](https://user-images.githubusercontent.com/55716109/163950051-87e6f0b5-ad88-4f00-9fe2-c0cf8966bac8.png)

## Definition of done
- [X] All acceptance criteria are completed.
- [X] The code has (at least) 80% branch test coverage.
- [X] All tests pass.
- [x] The code is reviewed and accepted by (at least) two other team members.
- [X] Views adhere to design style.

Closes #46

2022-04-19 08:29 UTC, martinjonsson01 requested changes
Great job! I've got a few comments regarding some of the tests and some implementation choices.

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Application/Contracts/IContractRepository.cs
> +    IEnumerable<Contract> Favorites();
This should be a get-only property instead of a method, just like `All` is. 

E.g.
`IEnumerable<Contract> Favorites { get; }`

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/ContractCard.razor
> +        </button>
Maybe it would be a good idea to extract this into its own component, to make the `ContractCard` less cluttered?

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Client/Pages/Contracts/ContractCard.razor
> +
Yeah, this doesn't feel like it should be the responsibility of a contract card, rather it's the responsibility of a favorite button component.

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Client/Pages/Dashboard/FavoriteCards.razor
> +    }
If it's possible, could you try using the `FetchData` component instead? For an example of how to use it, take a look at `ContractsPage`:
https://github.com/martinjonsson01/contract-portal/blob/e8ac5e42ee0ce05cf31120aef6138aacec6c00f1/src/Client/Pages/Contracts/ContractsPage.razor#L9-L19

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Client/Pages/Dashboard/FavoriteCards.razor
> +    }
These two will be unnecessary if you use `FetchData` since it's always the same for every data-fetching component. (Take a look at the source code for `FetchData` and you'll see.)

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Domain/Contracts/Contract.cs
> +    public bool IsFavorite { get; set; }
I'm liking the `IsFavorite` name instead of `Favorited` or `Favorite`, it makes the code more readable. 👍

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Server/Controllers/ContractsController.cs
> +        _contracts.UpdateContract(contract);
This is a nice way of doing it, I like it. It's very apparent that a contract is being temprarily "pulled out" of the application layer, applied a patch to, and then stuffed back in. It makes it very clear that the patch had to be done outside of the application, but that we don't want to do any more than necessary out here. 👍

2022-04-19 08:29 UTC, martinjonsson01 commented on src/Server/Server.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.4" />
Could you use the same version here as you did in the client? That is, `<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />`. It seems like this one in the server is some kind of AspNetCore-wrapper, so maybe not. But you should check.

2022-04-19 08:29 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Contracts/ContractCardTests.cs
> +           .Contain("M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z");
It's not very good to test that an exact SVG-icon is being used, since we might want to change that in the future without breaking the tests. Is it possible to check that the icon is visible through checking if an element with a class is rendered or not, instead?

2022-04-19 08:29 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Contracts/ContractCardTests.cs
> +        cut.Find(".bi-heart").InnerHtml.Should().Contain("m8 2.748-.717-.737C5.6.281 2.514.878 1.4");
Same here, this test is too tightly coupled to the implementation details.

2022-04-19 08:29 UTC, martinjonsson01 commented on tests/Presentation.Tests/Server/Controllers/ContractsControllerTests.cs
> +        IEnumerable<Contract> contracts = _cut.Search(null);
😳

2022-04-19 08:31 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Contracts/ContractCardTests.cs
> +           .Contain("M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z");
E.g. you put `id="filled-heart"` on the filled heart icon, and `id="empty-heart"` on the non-filled heart icon.

2022-04-19 09:02 UTC, Matte02 commented on src/Client/Pages/Contracts/ContractCard.razor
> +        </button>
It's a good idea, will try to do it.

2022-04-19 09:04 UTC, Matte02 commented on src/Client/Pages/Contracts/ContractCard.razor
> +        </button>
It's a good idea. Implementing it.

2022-04-19 11:31 UTC, Matte02 commented on src/Server/Server.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.4" />
I couldn't make it work. As the server is using more than just `Newtonsoft.Json` inside of `Microsoft.AspNetCore.Mvc.NewtonsoftJson`.

2022-04-19 11:32 UTC, Matte02 commented on tests/Presentation.Tests/Server/Controllers/ContractsControllerTests.cs
> +        IEnumerable<Contract> contracts = _cut.Search(null);
😆

2022-04-19 11:33 UTC, martinjonsson01 commented on src/Server/Server.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.4" />
Ah, fair enough.

2022-04-19 12:00 UTC, Matte02 commented on tests/Presentation.Tests/Client/Pages/Contracts/ContractCardTests.cs
> +           .Contain("M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z");
Changed it to check if it's not null and that the other couldn't be found.

2022-04-19 12:03 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Contracts/ContractCardTests.cs
> +           .Contain("M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z");
👍

2022-04-19 12:29 UTC, jonathan-lindqvist requested changes
Nice! Just some small nits and a comment about the tests that could be worth looking into! 😄

2022-04-19 12:29 UTC, jonathan-lindqvist commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +    /// </summary>
Hmmm this is true but feels too highlevel/wrong in this scenario since we change how a heart is rendered. Maybe something along the lines of "The contract to fetch favorite status from and to patch on status change"

2022-04-19 12:29 UTC, jonathan-lindqvist commented on tests/Application.Tests/Contracts/ContractServiceTests.cs
> +        contracts.Should().HaveCount(numberOfContracts);
Like @martinjonsson01 mentioned to me, in tests like this we are testing the mocked implementation. What we could test is that our service is implemented as expected, and we expect that our service call our repo. This can be done like this https://github.com/martinjonsson01/contract-portal/blob/e8ac5e42ee0ce05cf31120aef6138aacec6c00f1/tests/Application.Tests/Contracts/ContractServiceTests.cs#L48

2022-04-19 12:46 UTC, Matte02 commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +    /// </summary>
Good catch 👍

2022-04-19 13:00 UTC, jonathan-lindqvist approved these changes
lgtm!

2022-04-19 14:11 UTC, JacobBredin commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +            await OnFavoriteChange.InvokeAsync(Contract);
Perhaps updating the state of the contract should be done on the server side? I'm not sure what would be better.

2022-04-19 14:20 UTC, martinjonsson01 approved these changes
One last thing and then it's good to go!

2022-04-19 14:20 UTC, martinjonsson01 commented on src/Client/Pages/Dashboard/FavoriteCards.razor
> +                <em>Du har inga favorit markerade kontrakt.</em>
nit:
It's "favoritmarkerade" not "favorit markerade" 😝

2022-04-19 14:20 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Dashboard/FavoriteCardsTests.cs
> +        cut.Find("p em").TextContent.Should().Contain("Du har inga favorit markerade kontrakt.");
As you'll notice if you resolve my previous nit, this test will fail because it's too tightly coupled to the implementation. You shouldn't check for exact markdown, exact HTML tags, or exact anything. Instead, you should just verify that an element contains *any* text, or if you're looking for a specific element then use an id or a class.

2022-04-19 14:38 UTC, Matte02 commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +            await OnFavoriteChange.InvokeAsync(Contract);
What do you mean? It's done in the application. This is just updating the displayed contract, which it got from the server.

2022-04-19 14:51 UTC, JacobBredin commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +            await OnFavoriteChange.InvokeAsync(Contract);
No, are you not changing the IsFavorite property, converting the object to json and sending it to the server? Then on the server side, you find the object you modified and replace it. Shouldn't this modification all be done on server side? or am I misunderstanding this?

2022-04-19 15:09 UTC, Matte02 commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +            await OnFavoriteChange.InvokeAsync(Contract);
`patchDocument` is just telling how it should be "patched"(updated). The update itself is done in server. 
![image](https://user-images.githubusercontent.com/55716109/164035935-84a953ca-4865-4d17-97ef-0808d60efc39.png)

2022-04-19 15:18 UTC, JacobBredin commented on src/Client/Pages/Contracts/FavoriteButton.razor
> +            await OnFavoriteChange.InvokeAsync(Contract);
Okay, I read up on patching, now I understand. All good 👍

2022-04-19 18:45 UTC, Matte02 commented on tests/Presentation.Tests/Client/Pages/Dashboard/FavoriteCardsTests.cs
> +        cut.Find("p em").TextContent.Should().Contain("Du har inga favorit markerade kontrakt.");
Added a div with a ID. Should be possible to change the text inside of it to anything and still pass the test.

2022-04-20 03:02 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Dashboard/FavoriteCardsTests.cs
> +        cut.Find("p em").TextContent.Should().Contain("Du har inga favorit markerade kontrakt.");
Nice 👍

2022-04-20 06:25 UTC, merged