15 adding users
martinjonsson01/contract-portal pull request #75
Opened 2022-04-20 15:39 UTC by pkasinski

## Summary

Adds an input form on the admin page that enables admins to add users.

![Screen Shot 2022-04-20 at 17 37 39](https://user-images.githubusercontent.com/83813240/164269210-9cd97078-6cba-461e-bf7c-b2a584d541ba.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [x] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #15

2022-04-20 16:03 UTC, martinjonsson01 approved these changes
Nice job! I've got no real issues with the code, rather a whole bunch of nitpicks and best-practices that I think is worth taking a look at.

2022-04-20 16:03 UTC, martinjonsson01 commented on tests/Presentation.Tests/Server/Controllers/UsersControllerTests.cs
> +    }
Very nice, this is exactly what a controller test class should look like. It should only be testing controller-specific logic, and since we have all of our real logic in the Application layer then that means that controller tests should only be testing the HTTP-return values. 👍

2022-04-21 07:45 UTC, pkasinski commented on src/Domain/Users/User.cs
> +    public DateTime LatestPaymentDate { get; set; }
I tried to set it to default(DateTime) but the IDE suggests to remove it.

2022-04-21 14:57 UTC, martinjonsson01 commented on src/Domain/Users/User.cs
> +    public DateTime LatestPaymentDate { get; set; }
Did `DateTime.MinValue` not work?

2022-04-21 15:01 UTC, jonathan-lindqvist requested changes
Really nice, just left a comment for the frontend part regarding the layout 😄

2022-04-21 15:07 UTC, martinjonsson01 commented on src/Client/Pages/Admin/AdminPage.razor
Well, with regards to the planned layout we have basically not been following it in any of our stories so far. I'm not sure this is the story to implement it, I'm thinking we're going to have to make two dedicated stories for implementing both (the top-bar) and (the admin-page layout and tabs).

But it's true that if we want to be strictly vertical then maybe it should be done within a story like this one...

2022-04-21 15:10 UTC, martinjonsson01 commented on src/Domain/Users/User.cs
> +    public DateTime LatestPaymentDate { get; set; }
I totally agree with the style guide saying `= default(DateTime)` is unnecessary because it definitely is (the `default` operator returns the value that an unitialized variable of that type gets automatically). I think it's more valuable to specifically say that we're using the minimum possible value of a date and time. But if that isn't possible for some reason then maybe it's better to just leave it without any explicit default value.

2022-04-21 19:13 UTC, Matte02 approved these changes
Looks good!

![image](https://user-images.githubusercontent.com/55716109/164535890-af1e22d8-4e16-4dac-9778-ffcdb5732d69.png)
Any reason you haven't checked this box? You have more than 80% since the PR is passing the check.

2022-04-21 20:10 UTC, ellsib approved these changes
LGTM. Also easy to follow with all the comments 👍 Regarding Jonathan's comment I think we will have to modify that for many user stories later on anyways, so this could be fine atm.

2022-04-22 06:57 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/AdminPage.razor
👍

2022-04-22 06:57 UTC, jonathan-lindqvist approved these changes
Neat!

2022-04-22 07:16 UTC, merged