60 basic company name search
martinjonsson01/contract-portal pull request #76
Opened 2022-04-21 15:50 UTC by jonathan-lindqvist

## Summary
Add search engine module to search for the supplier name.

![image](https://user-images.githubusercontent.com/47867973/164500130-6fa6c6f1-e62d-4761-b920-faa03411b7b2.png)

![image](https://user-images.githubusercontent.com/47867973/164500254-ac93e760-24d4-459d-ab5d-4ed7d0560c30.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #60

2022-04-21 15:55 UTC, martinjonsson01 requested changes
I'm not a fan of the duplicated code 😩

2022-04-21 15:55 UTC, martinjonsson01 commented on src/Application/Search/Modules/SupplierNameSearch.cs
> +               query.Contains(entity.SupplierName, StringComparison.OrdinalIgnoreCase);
I'm wondering if there's a nice way to not have duplicated code between this and the `TitleSearch` module. We could have them both inherit from a superclass but we should generally try to avoid unnecessary inheritance and instead prefer composition. Could you perhaps break out the matching into something like a `TitleMatcher` class and just delegate to an instance of it within the two search modules, maybe?

Right now it's no issue but I can imagine that in the future when we want to make the title searching more robust, we'll have to modify two places and if we forget to do that then that'll be not-good. 😛

2022-04-21 15:55 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/ContractSupplierNameSearchModuleTests.cs
> +}
I'm imagining this is a copy-paste of the tests for the `NameSearch` module? lol

These will be very annoying to change in two places whenever we want to update how title searching works, I think it's best to consolidate into a single implementation and only test that single implementation.

2022-04-21 17:18 UTC, martinjonsson01 commented on src/Application/Search/Modules/SupplierNameSearch.cs
> +               query.Contains(entity.SupplierName, StringComparison.OrdinalIgnoreCase);
I fix

2022-04-21 17:18 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/ContractSupplierNameSearchModuleTests.cs
> +}
I fix

2022-04-21 17:19 UTC, martinjonsson01 approved these changes
Wow, @martinjonsson01 you did such a great job ily 😍

2022-04-21 17:20 UTC, martinjonsson01 commented
![image](https://user-images.githubusercontent.com/12572888/164515996-1d47b3a1-11b8-4218-a6f2-3150a70081e9.png)

2022-04-21 17:30 UTC, JacobBredin commented
> Wow, @martinjonsson01 you did such a great job ily 😍



> Wow, @martinjonsson01 you did such a great job ily 😍

🖐️ You are under arrest 🚓

⚖️ Self review is prohibited by the law 👨‍⚖️

2022-04-21 18:03 UTC, martinjonsson01 commented
> > Wow, @martinjonsson01 you did such a great job ily 😍
> 
> 🖐️ You are under arrest 🚓
> 
> ⚖️ Self review is prohibited by the law 👨‍⚖️

😨

2022-04-21 19:53 UTC, Matte02 approved these changes
LGTM!

2022-04-21 19:59 UTC, XwayTomy approved these changes
The summary is a bit weird but otherwise it looks good! GJ!

2022-04-22 06:56 UTC, jonathan-lindqvist reviewed
👍

2022-04-22 14:34 UTC, merged