61 description search
martinjonsson01/contract-portal pull request #77
Opened 2022-04-22 13:09 UTC by JacobBredin

## Summary
Add a new search module called SubstringSearch, which matches the substrings of a query with the specified text to match against.

For example, if a contract has the description _"We build great bridges over rivers and lakes"_ and we will get a match against the query: _"build bridges lakes"_. This also works for any order: i.e. _"build lakes bridges"_.

Searching for parts of a contract description or supplier description now works in the contract search bar.

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #61

2022-04-22 14:58 UTC, martinjonsson01 requested changes
Nice! I'm worried about the redundant tests, though.

2022-04-22 14:58 UTC, martinjonsson01 commented on src/Application/Search/Modules/SubstringSearch.cs
> +public class SubstringSearch : ISearchModule<Contract>
nit:
This name is a bit too general, as the other search module we've currently is `TitleMatcher` but it also uses substring matching (`.contains(...)`). Maybe it could be renamed to something that matches what we're actually using it for, like `BodyTextSearch` (since it searches body-text instead of short titles).

2022-04-22 14:58 UTC, martinjonsson01 commented on src/Application/Search/Modules/SubstringSearch.cs
> +    /// <returns>Whether the contract property matches the substrings of the query or not.</returns>
nit:
Be careful not to describe implementation details in the documentation/naming. As a caller of this method I don't care that it's matching substrings, I just care whether it matches or not.

2022-04-22 14:58 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/SubstringSearchModuleTests.cs
> +    public void Match_ReturnsTrue_WhenQueryContainsMultipleSubstringsOfDescription()
It feels like you've got redundant tests here. 

Isn't this test and `Match_ReturnsTrue_WhenQueryContainsPartOfMultipartName` testing exactly the same thing twice?

2022-04-22 14:58 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/SubstringSearchModuleTests.cs
> +    public void Match_ReturnsTrue_WhenQueryIsSameAsDescription()
This test is just like `Match_ReturnsTrue_WhenQueryContainsMatchingName`, they're testing the same thing twice which is redundant.

If we were to change the requirements in the future so that these tests are affected then we'd have to fix all the duplicated tests as well. The goal is to have only a single test fail for a single reason, so having multiple tests fail for the same reason is not good.

2022-04-22 14:58 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/SubstringSearchModuleTests.cs
> +    public void Match_ReturnsTrue_WhenQueryContainsSubstringOfDescription()
The functionality being tested here is also covered by `Match_ReturnsTrue_WhenQueryContainsMatchingSubstring`, so you've got to pick one and run with it.

2022-04-22 14:58 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/SubstringSearchModuleTests.cs
> +    public void Match_ReturnsFalse_WhenQueryContainsMultipleWordsAbsentFromTheDescription()
nit:
```suggestion
    public void Match_ReturnsFalse_WhenQueryIsEntirelyDifferentFromDescription()
```

2022-04-22 14:58 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/SubstringSearchModuleTests.cs
> +        _cutName = new SubstringSearch(contract => contract.Name);
These two instances test the exact same functionality, so you don't need tests for both of these, testing on one of them is enough.

But what's important to test (and what you might've been getting at with writing it this way) is that the search module *does* take the selector into account. For the `TitleSearch` module I did this with a single test that swapped the component under test for one with a different selector. We don't want to duplicate our testing efforts.

2022-04-22 15:05 UTC, JacobBredin commented on src/Application/Search/Modules/SubstringSearch.cs
> +public class SubstringSearch : ISearchModule<Contract>
Yeah, I struggled with finding a good name. That's a good suggestion. I'll change it 👍

2022-04-22 15:17 UTC, JacobBredin commented on tests/Application.Tests/Search/Modules/SubstringSearchModuleTests.cs
> +    public void Match_ReturnsTrue_WhenQueryContainsMultipleSubstringsOfDescription()
You are right, I'm going to check the tests again 👍

2022-04-22 15:58 UTC, JacobBredin commented on tests/Application.Tests/Search/Modules/SubstringSearchModuleTests.cs
> +    public void Match_ReturnsTrue_WhenQueryIsSameAsDescription()
I removed some of the tests, please take a look 🙂

2022-04-22 16:10 UTC, martinjonsson01 approved these changes
Looks good, nicely done.

2022-04-22 16:10 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +}
The only test you're missing is one that actually verifies that you haven't hardcoded the search module to only work on descriptions. This is easily tested by having a single test that uses another property, like the supplier description:
```suggestion
    [Fact]
    public void Match_ReturnsTrue_WhenMatchingSelectedProperty()
    {
        // Arrange
        _cut = new BodyTextSearch(contract => contract.SupplierDescription);
        
        const string supplierDescription = "Describes supplier";
        var contract = new Contract { Description = "Describes contract", SupplierDescription = supplierDescription, };
        
        // Act
        bool matches = _cut.Match(contract, supplierDescription);
        
        // Assert
        matches.Should().BeTrue();
    }
}
```

2022-04-23 15:16 UTC, jonathan-lindqvist approved these changes
Left one nit, otherwise super! 👍

2022-04-23 15:16 UTC, jonathan-lindqvist commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
NIT: Any specific reason we want to return false? In the title/name search we did the opposite, we reasoned that the empty string is part of every string, like the how the empty set is part of every set. It doesn't really change anything but might be nice to be consistent

2022-04-23 16:35 UTC, JacobBredin commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
Okay, I didn't know that was the reason you matched on empty strings. I thought it was because you wanted to show contracts if there were nothing entered in the search box.

I reasoned that an empty strings should have no match since there is nothing being searched. I'm open to changing it. However I do think it makes more sense from a search perspective to not match on empty strings.

2022-04-23 16:37 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
We could have the empty-string-matching be a thing that only happens in the titles so that an empty query gives back all contracts. Although that feels a bit iffy since it'd just be by convention with no real enforcement of it. 

I can imagine that there are downsides to matching everything on empty strings, especially when it comes to performance later on. But that shouldn't be our main concern at the moment.

2022-04-23 16:40 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
At the moment it doesn't really matter though, and as long as the tests are clear about which implementation decision has been made for each module then it'll be easy to look back later on an change it if need be.

2022-04-23 16:44 UTC, JacobBredin commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
We could add a search module that matches when the string is empty 🧠

2022-04-23 16:45 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
![image](https://user-images.githubusercontent.com/12572888/164915473-3494c308-2d36-4f3f-bcf2-7844ca6475cd.png)
you're a genius!

For real, though, that sounds like the best option here lol

2022-04-23 16:46 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
That is, we make all the individual modules never match on empty strings, and have a specific module that matches anything on empty strings.

Question is if it belongs in this PR or a hotfix?

2022-04-23 16:48 UTC, JacobBredin commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
A hotfix would be best, since we would need to modify simpleTextSearch also

2022-04-23 16:51 UTC, martinjonsson01 commented on tests/Application.Tests/Search/Modules/BodyTextSearchModuleTests.cs
> +    }
Yeah, fair enough. 👍

2022-04-23 16:52 UTC, merged