23 show users
martinjonsson01/contract-portal pull request #78
Opened 2022-04-22 15:42 UTC by pkasinski

## Summary
Adds the ability to see which users have been added on the admin page.

![Screen Shot 2022-04-22 at 17 38 47](https://user-images.githubusercontent.com/83813240/164748150-adb045b5-b436-4418-a9e5-8cb7b1b55f28.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [x] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #23

2022-04-22 18:52 UTC, martinjonsson01 requested changes
Nice! 

I very much appreciate that you follow the existing conventions for how we've implemented the contracts list on the admin page. 

But I'm wondering why you've got search functionality for the users, that seems out-of-scope (and not really needed at all, really). If it's accidental from copying the implementation of how we did it with contracts, then in the future try to think about if what you're copying from really is the exact same scenario, or if you need to modify it slightly!

2022-04-22 18:52 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserForm.razor
> +    public EventCallback<User> OnUserAdded { get; set; } = EventCallback<User>.Empty;
nit:
Why rename it back to `OnUserAdded`?

2022-04-22 18:52 UTC, martinjonsson01 commented on src/Application/Users/IUserService.cs
> +    IEnumerable<User> Search(string query);
Is this necessary for this user story?

2022-04-22 18:52 UTC, martinjonsson01 commented on src/Application/Users/UserService.cs
> +    }
I don't see the need for searching for users using queries, is it just a remnant of copy/pasting?

2022-04-22 18:52 UTC, martinjonsson01 commented on src/Server/Controllers/UsersController.cs
> +    }
In the `ContractsController` I refactored it such that the `GetAll` and `Search` endpoints were merged into one, like you've done here for the `UsersController`. But I did that because we want to be able to search for contracts, does the same hold for users? And even if it did, should that be in this story? 

What I'm thinking you should probably do here instead is remove the search and query parts and just make it into a `All`  endpoint that just plainly fetches and returns all users.

2022-04-22 18:52 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserListItem.razor
> +<div id="@User.Name" class="list-group-item d-flex justify-content-between" style="max-width: 50%">
It's not a good idea to use user-input data as id values. There are strict requirements for how ids can be formatted (e.g. they can't contain spaces), which aren't enforced for things like user's names. If there's a user ID then that is a better option, but keep in mind that HTML-ids have to begin with a letter so if you're using a GUID then you'll have to prefix it with something like `$"id_{guid}"}`.

2022-04-22 18:52 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Admin/UserListTests.cs
> +    public void AddingContract_RendersTheNewContract()
If you're going to copy and paste code, please make sure to rename it as well 😝

2022-04-23 11:23 UTC, pkasinski commented on src/Client/Pages/Admin/UserForm.razor
> +    public EventCallback<User> OnUserAdded { get; set; } = EventCallback<User>.Empty;
I think the name OnUserAdded makes more sense when you see it in context in AdminPage.razor.

2022-04-23 11:33 UTC, pkasinski commented on src/Application/Users/IUserService.cs
> +    IEnumerable<User> Search(string query);
I'm not sure. I was looking at the implementation of ContractList and it seems to call Search in ContractsController which delegates to IContractService when it tries to get the contracts. I thought that it would be reasonable to implement UserList in the same way.

2022-04-23 11:37 UTC, pkasinski commented on src/Application/Users/IUserService.cs
> +    IEnumerable<User> Search(string query);
I'm not sure. I was looking at the implementation of ContractList and it seems to call Search in ContractsController which delegates to IContractService when it tries to get the contracts. I thought that it would be reasonable to implement UserList in the same way.

2022-04-23 11:38 UTC, pkasinski commented on src/Application/Users/IUserService.cs
> +    IEnumerable<User> Search(string query);
Looking at your other comments, I don't think it is necessary.

2022-04-23 11:38 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserForm.razor
> +    public EventCallback<User> OnUserAdded { get; set; } = EventCallback<User>.Empty;
Ok

2022-04-23 13:00 UTC, martinjonsson01 approved these changes
lgtm 👍

2022-04-23 13:02 UTC, martinjonsson01 commented
As for the failing test in `AdminPageTests`, it should be enough that you include a mock of a stub-endpoint that just returns an empty list of users (since those tests don't care about the users being shown), like this but for users and with an empty list:
https://github.com/martinjonsson01/contract-portal/blob/52f5539109d0852de609dc5e3ce83f5fbf7d0807/tests/Presentation.Tests/Client/Pages/Admin/AdminPageTests.cs#L39

2022-04-23 15:30 UTC, jonathan-lindqvist approved these changes
Noice! Just one small change, but will approve this since it is a really small change 😄

2022-04-23 15:30 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/UserListItem.razor
> +    Senaste betaldatum: @User.LatestPaymentDate.ToShortDateString()
Each of these should be placed within  paragraph tags, `<p>UR TEXT HERE </p>`. This way they will newline (unless css says otherwise) and we have the possibility to add classes similar attributes with ease. Also they will follow the same styling as the rest of the site, if there are any styling for `p` right now or that we add in the future.

2022-04-23 16:04 UTC, merged