65 search result weighting
martinjonsson01/contract-portal pull request #81
Opened 2022-04-23 16:54 UTC by martinjonsson01

## Summary
Adds ranking of search results based on which property the query was matched.

In the first example in the gif, the contract with the SJ-logo has "SJ" both in its title and its supplier name, meaning it gets ranked above the other contract which only has "SJ" in its title.
In the second example in the gif, the contract with the train image has the word "Tåg" in all three of its properties, so it is ranked above the other two contracts which only have "Tåg" in one or two of their properties.
![chrome_tx7kJ1wkDX](https://user-images.githubusercontent.com/12572888/164915235-0c1ae248-ba94-40ca-b656-47e95524ea70.gif)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #65

2022-04-23 17:57 UTC, JacobBredin requested changes
Looks good, nice solution, very close to done 😊

However, I think you need to refactor the methods in SearchEngine before you merge, take a look at my comments below🧙

2022-04-23 17:57 UTC, JacobBredin commented on src/Application/Search/SearchEngine.cs
> +                select (entity, module)).ToList();
This reads like a magical spell lol 🧙

Very easy to read 👍

2022-04-23 17:57 UTC, JacobBredin commented on src/Application/Search/SearchEngine.cs
> +    private ICollection<(TEntity entity, ISearchModule<TEntity> module)> FindMatches(
I think it would be better to just return the weight instead of the module in the tuple, it ends up creating more complexity then necessary.

2022-04-23 17:57 UTC, JacobBredin commented on src/Application/Search/SearchEngine.cs
> +    private static IEnumerable<(TEntity entity, double maxWeight)> FindWeights(
In my opinion the name is a bit of a misnomer, since it really calculates the total weight. 

In light of my other suggestion below about `FindMatches` instead returning the tuple `(TEntity entity, double weight)`. 

I think it would make the code simpler if this function just calculated the total weight of each contract. Instead of also retrieving the associated weight.

2022-04-23 17:57 UTC, JacobBredin commented on src/Application/Search/SearchEngine.cs
> +        return SortByWeights(entitiesWithWeights);
A bit hard to read, because of the long types 😢

If you make the changes I suggest below, it might get better 🙂

2022-04-23 18:07 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +    private ICollection<(TEntity entity, ISearchModule<TEntity> module)> FindMatches(
Sure, I can change it to that. But I don't see how that is more complex?

Or what complexity is it you're talking about, because I don't really consider this an improvement in complexity:
![image](https://user-images.githubusercontent.com/12572888/164934344-aa79adb8-4183-4172-8bce-f8e6e259e0bb.png)

2022-04-23 18:16 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +    private static IEnumerable<(TEntity entity, double maxWeight)> FindWeights(
Well, what it does is get all distinct entities and *find* their *weights* and sums them and returns it together with the entity. I picked out the central purpose of the method and named it that, because `FindSumOfWeightsOfDistinctEntities` doesn't really roll of the tongue lol

> I think it would make the code simpler if this function just calculated the total weight of each contract. Instead of also retrieving the associated weight.

I don't follow what you mean. The calculating of the total weight is done by row 46: `let maxWeight = weights.Sum()`, do you want that to be a separate method? The retrieving of the associated weight, do you mean on line 45 where it did `.Select(pair => pair.module.Weight)`? 
Or did you mean the first part of the method that sorts out duplicated entities and then gets the weights of the remaining entities?

2022-04-23 18:17 UTC, JacobBredin commented on src/Application/Search/SearchEngine.cs
> +    private ICollection<(TEntity entity, ISearchModule<TEntity> module)> FindMatches(
My bad. I thought it was possible to remove one line from `FindWeights` and make it a bit more readable. No, I'm not really sure how to make it simpler. 😢

2022-04-23 18:17 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +        return SortByWeights(entitiesWithWeights);
Ohh, is that what you're talking about? Just the types?

We could use var here instead, if that's all you're worried about.

2022-04-23 18:17 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +        return SortByWeights(entitiesWithWeights);
The downside with using var like that is that you won't be able to see at all what the actual types are, you'll have to go down into the methods.

2022-04-23 18:18 UTC, JacobBredin commented on src/Application/Search/SearchEngine.cs
> +        return SortByWeights(entitiesWithWeights);
Yeah, don't do that.

2022-04-23 18:21 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +    private ICollection<(TEntity entity, ISearchModule<TEntity> module)> FindMatches(
Hmm, did you mean something like this?

![image](https://user-images.githubusercontent.com/12572888/164934677-5701ceff-bf4c-4020-891d-9c92709ccd98.png)

This improves the readability of the actual LINQ-expression, but at the cost of adding another method and another variable, with all the boilerplate that comes around that.

2022-04-23 18:22 UTC, JacobBredin commented on src/Application/Search/SearchEngine.cs
> +    private static IEnumerable<(TEntity entity, double maxWeight)> FindWeights(
My original thought was that the function did too many things at once. I think something like `CalculateTotalWeights` would be an appropriate name, if `.Select(pair => pair.module.Weight)` was changed to `.Select(pair => pair.weight)`.

2022-04-23 18:25 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +    private static IEnumerable<(TEntity entity, double maxWeight)> FindWeights(
![image](https://user-images.githubusercontent.com/12572888/164935324-2d0a91fa-4ff2-4418-92be-bc184408a551.png)

Like that?

I'm not really changing what the method is doing, just renaming stuff

2022-04-23 18:26 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +    private static IEnumerable<(TEntity entity, double maxWeight)> FindWeights(
The problem with trying to break up these LINQ-expressions is that they're highly coupled, e.g. the lines that use the `entity` and `weights` variables depend on the lines that define them using the `from` and `let` keywords.

2022-04-23 18:33 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +    private ICollection<(TEntity entity, ISearchModule<TEntity> module)> FindMatches(
Feel free to play around with the source code, it's a lot easier than trying to explain what you mean in text and you get quicker feedback on what works and what doesn't

2022-04-24 09:36 UTC, XwayTomy approved these changes
Looks good! See comments attached to the review made by Ella

2022-04-24 09:37 UTC, ellsib approved these changes
Good job, I have some minor comments/questions but I don't see any reason to not approve :)

2022-04-24 09:37 UTC, ellsib commented on src/Application/Contracts/ContractService.cs
> +        _search.AddModule(new SimpleTextSearch(contract => contract.Name, 5d));
Are the weights set here? (5d, 1d etc) Maybe add a comment in order to easily find where to change the weight if anyone at Prodigo wants to do that.

2022-04-24 09:37 UTC, ellsib commented on tests/Application.Tests/Search/SearchEngineTests.cs
> +        actual.Should().BeEquivalentTo(new[] { 2, 4, 6, });
Why should 2,4,6 come up when you search for 2? Aka why should it be divisible? 
The previous test where {1,1,1,2,3} results in {1,1,1} when searching for 1 made more sense to me.

2022-04-24 09:38 UTC, martinjonsson01 commented on src/Application/Search/SearchEngine.cs
> +               let maxWeight = weights.Sum()
Oh, you're absolutely right. The first implementation I did used the maximum, but I later on changed it to the sum and forgot to rename the variable. 👍 

```suggestion
               let totalWeight = weights.Sum()
```

2022-04-24 09:40 UTC, martinjonsson01 commented on src/Application/Contracts/ContractService.cs
> +        _search.AddModule(new SimpleTextSearch(contract => contract.Name, 5d));
Yeah. I'll clarify that the numbers are the weights, but I think a more detailed documentation around how to add/remove/configure search modules needs to be written separately when we decide to prioritize that.

2022-04-24 09:41 UTC, ellsib commented on src/Application/Contracts/ContractService.cs
> +        _search.AddModule(new SimpleTextSearch(contract => contract.Name, 5d));
Alright, sounds good!

2022-04-24 09:45 UTC, martinjonsson01 commented on tests/Application.Tests/Search/SearchEngineTests.cs
> +        actual.Should().BeEquivalentTo(new[] { 2, 4, 6, });
>The previous test where {1,1,1,2,3} results in {1,1,1} when searching for 1 made more sense to me.

Yeah the previous test looked a bit nicer, but doesn't work with integers since they're primitive values and therefore you can't distinguish between `1`, `1` and `1`. 

The problem with the old test was that we don't want to return duplicated contracts even if it matches in multiple places, so I made it remove all duplicates by comparing references. Since the tests here use integers to exemplify that the search engine can search through anything, it couldn't use the same value. 

>Why should 2,4,6 come up when you search for 2? Aka why should it be divisible?

Because this test is using the `DivisibleMatcher`, meaning it matches if the entity is divisible by the number in the query. `2`, `4` and `6` are all multiples of `2` (`2*1`, `2*2`, `3*2`), so they're all matched.

2022-04-24 09:58 UTC, Matte02 approved these changes
Good work 👍

2022-04-24 10:03 UTC, JacobBredin approved these changes
LGMT APPROVED

2022-04-24 10:08 UTC, merged