19 Removing users
martinjonsson01/contract-portal pull request #93
Opened 2022-04-27 13:25 UTC by JacobBredin

## Summary
A remove button has been added to each UserListItem on the admin page. The list of users is now a table. The contracts list has also been updated to the same style.

![image](https://user-images.githubusercontent.com/70701264/165528025-bdaaf0aa-0ee4-4252-a9a0-5cb715622299.png)

![image](https://user-images.githubusercontent.com/70701264/165528000-5e0b693a-26ed-41b6-a22f-7b6b6028a77d.png)

## Definition of done
- [x] All acceptance criteria are completed.
- [x] The code has (at least) 80% branch test coverage.
- [x] All tests pass.
- [ ] The code is reviewed and accepted by (at least) two other team members.
- [x] Views adhere to design style.

Closes #19

2022-04-27 14:21 UTC, pkasinski approved these changes
Looks good! I left a few comments about minor things which could possibly be improved.

2022-04-27 14:21 UTC, pkasinski commented on src/Client/wwwroot/css/app.css
> +    color: #ffffff;
Nit: I think it would be better to use the variables defined at the top of app.css here.

2022-04-27 14:23 UTC, martinjonsson01 requested changes
Great job! 

I think you should resolve the duplicated code in the modals, though.
And one of the tests are incorrect.

2022-04-27 14:23 UTC, martinjonsson01 commented on src/Application/Users/IUserService.cs
> +    /// <returns>whether the removal was successful.</returns>
nit:
```suggestion
    /// <param name="id">User to be removed.</param>
    /// <returns>Whether the removal was successful.</returns>
```

2022-04-27 14:23 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractRemoveModal.razor
> +<div class="modal fade" id="@($"modal_{Contract.Id}")" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
nit:
Take a look at the ids used here, I don't think you've changed them from the bootstrap example code. (e.g. `exampleModalLabel`)

2022-04-27 14:23 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserList.razor
> +    // can not be null when remove button is pressed.
nit:
```suggestion
        // Using null forgiving operator because because _users
        // can not be null when remove button is pressed.
```

2022-04-27 14:23 UTC, martinjonsson01 commented on tests/Presentation.Tests/Client/Pages/Admin/UserListTests.cs
> +        cut.FindAll($"#user_id_").Should().NotContain(elementWithNewName);
`cut.FindAll($"#user_id_")` does not return all elements with ids that begin with `user_id_`, even though it may look like it should. The CSS ids are matched exactly, so no wildcards allowed. 

Since this test is trying to make sure that a removed user is no longer rendered, you should be checking for the removed user's id, something like `$"user_id_{removedUser.Id}"`.

2022-04-27 14:24 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserList.razor
> +    private void OnUserRemoved(User user)
I agree, but I think that using the word `Handle` is way too generic, so the latter is a better choice.

2022-04-27 15:26 UTC, JacobBredin commented on src/Client/Pages/Admin/UserListItem.razor
> +<tr class="user-list-item" id=@($"user_id_{User.Id}")>
Should I also change UserList to UserTable?

2022-04-27 17:01 UTC, JacobBredin commented on src/Client/Pages/Admin/ContractRemoveModal.razor
> +<div class="modal fade" id="@($"modal_{Contract.Id}")" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
Removed 👍

2022-04-27 17:03 UTC, JacobBredin commented on src/Client/Pages/Admin/UserRemoveModal.razor
> +}
I have done a refactor and moved the code that does the HTTP call to the server to UserTable (formerly UserList) and the same for ContractTable. See what you think

2022-04-27 17:16 UTC, martinjonsson01 approved these changes
lgtm 👍 

Just a few comments

2022-04-27 17:16 UTC, martinjonsson01 commented on src/Client/Pages/Admin/ContractTable.razor
> +    private async void Remove(Contract contract)
It's bad practice to have `async void` methods, they should always be of type `Task` if they're asynchronous.

```suggestion
    private async Task Remove(Contract contract)
```

2022-04-27 17:16 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserTable.razor
> +        InvokeAsync(StateHasChanged);
Shouldn't this send a `DELETE` message to the server, or where are you doing that for users?

2022-04-27 17:17 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserTable.razor
> +        InvokeAsync(StateHasChanged);
And pls indent the comments correctly 😩

2022-04-27 17:19 UTC, JacobBredin commented on src/Client/Pages/Admin/UserTable.razor
> +        InvokeAsync(StateHasChanged);
bro no

2022-04-27 17:21 UTC, JacobBredin commented on src/Client/Pages/Admin/UserTable.razor
> +        InvokeAsync(StateHasChanged);
I think I made a mistake + I broke 90% of all tests 😨

2022-04-27 17:23 UTC, martinjonsson01 commented on src/Client/Pages/Admin/UserTable.razor
> +        InvokeAsync(StateHasChanged);
Looks like you just forgot to rename a bunch of references to the list components

2022-04-28 06:58 UTC, JacobBredin commented on tests/Presentation.Tests/Client/Pages/Admin/UserListTests.cs
> +        cut.FindAll($"#user_id_").Should().NotContain(elementWithNewName);
Should be solved now 👍

2022-04-28 06:59 UTC, JacobBredin commented on src/Client/wwwroot/css/app.css
> +    color: #ffffff;
Fixed 😄

2022-04-28 06:59 UTC, JacobBredin commented on src/Client/Pages/Admin/UserList.razor
> +    private void OnUserRemoved(User user)
I've changed what the method does, see if you agree with the new name 😊

2022-04-28 06:59 UTC, JacobBredin commented on src/Application/Users/IUserService.cs
> +    /// <returns>whether the removal was successful.</returns>
Fixed 🖋️

2022-04-28 07:00 UTC, jonathan-lindqvist reviewed
Halfway through the review and found two things that might be good to take a look at 👍

2022-04-28 07:00 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/RemoveModal.razor
> +    <div class="modal-content">
NIT: can these be combined into one div?
Just feels like there are a lot of divs :p

2022-04-28 07:00 UTC, jonathan-lindqvist commented on src/Client/wwwroot/css/app.css
> +}
[Bootstrap](https://getbootstrap.com/docs/5.1/utilities/shadows/) has shadows you can use.

Also you should be able to use [flex](https://getbootstrap.com/docs/5.1/utilities/flex/#justify-content) to move the text around. But unsure if it will work within tables.

2022-04-28 13:40 UTC, JacobBredin commented on src/Client/Pages/Admin/RemoveModal.razor
> +    <div class="modal-content">
I'm not sure how it would be done, because removing the div breaks the formatting of the modal dialog. If you have a working suggestion we could change it, but I don't think we should prioritize it

2022-04-28 13:42 UTC, martinjonsson01 approved these changes
very najs 👍

2022-04-28 13:51 UTC, martinjonsson01 reviewed
Seems a file that should be deleted by now made it through the merge 😨

2022-04-28 13:51 UTC, martinjonsson01 commented on src/Infrastructure/Users/FakeUserRepository.cs
> +}
This file should no longer exist.

2022-04-28 13:54 UTC, JacobBredin commented on src/Infrastructure/Users/FakeUserRepository.cs
> +}
I knew it! It is a ZOMBIE file!

2022-04-28 13:56 UTC, martinjonsson01 commented on src/Infrastructure/Users/FakeUserRepository.cs
> +}
![image](https://user-images.githubusercontent.com/12572888/165768642-ec9f97c4-25f6-44f0-b872-d201ec90ba37.png)
oh god everybody run oh frick oh crap

2022-04-28 15:40 UTC, jonathan-lindqvist commented on src/Client/Pages/Admin/RemoveModal.razor
> +    <div class="modal-content">
👍

2022-04-28 17:37 UTC, merged